### ISSUE TITLE
Unable to build RPR on ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by zakkos** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#101]
Trying to build RPR 9ab8ed983de7ae23fcf87a78e57b4ea565c06e85 on a linux ubuntu 20.04 LTS machine. After installing all the dependencies when I get to the actual build this is the error I get:

```bash
$ python3 build.py
Traceback (most recent call last):
  File "rpr.py", line 151, in <module>
    export('pyrprwrapapi.json', [], 'rprwrap.h', 
  File "rpr.py", line 41, in export
    write_api(api_desc_fpath, f, abi_mode)
  File "rpr.py", line 114, in write_api
    api = pyrprapi.load(api_desc_fpath)
  File "src/pyrprapi.py", line 183, in load
    loader = json.load(open(fpath),
FileNotFoundError: [Errno 2] No such file or directory: 'src/pyrprwrapapi.json'
Traceback (most recent call last):
  File "build.py", line 43, in <module>
    subprocess.check_call([sys.executable, 'rpr.py'])
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'rpr.py']' returned non-zero exit status 1.
```

**Comment by bnagirniak** [comment]
Please run ./build.sh script.

**Comment by zakkos** [comment]
> Please run ./build.sh script.
> Also it is important to have python3.7.

Got it. I wasn't using python3.7. My bad.
