### ISSUE TITLE
Unable to load from fresh plugin install

### ISSUE THREAD

**Issue by pgedeon** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#175]
2020-12-27 08:42:16,300 rpr.engine.init [13336]: INFO RPR Core version: 2.1.8 build 0x3f5410b0
2020-12-27 08:42:16,335 rpr.engine.init [13336]: INFO Image Filters version 1.6.1 build 0xe4886697
2020-12-27 08:42:16,339 rpr.default [13336]: INFO rprsdk_bin_path: C:\Users\peter\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\rprblender
2020-12-27 08:42:18,861 rpr.material_library [13336]: INFO Material library located at C:\ProgramData\RadeonProRender\MaterialLibrary\Xml
2020-12-27 08:42:30,404 rpr.viewport_engine [19984]: ERROR IoError: could not get size of file ..\..\..\..\..\..\..\..\ EXCEPTION: Traceback (most recent call last):
  File "C:\Users\peter\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\rprblender\engine\viewport_engine.py", line 428, in _do_sync_render
    self._do_sync(depsgraph)
  File "C:\Users\peter\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\rprblender\engine\viewport_engine.py", line 259, in _do_sync
    frame_current=frame_current)
  File "C:\Users\peter\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\rprblender\export\object.py", line 57, in sync
    openvdb.sync(rpr_context, obj, **kwargs)
  File "C:\Users\peter\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\rprblender\export\openvdb.py", line 116, in sync
    grids = helper_lib.vdb_read_grids_list(vdb_file)
  File "C:\Users\peter\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\rprblender\utils\helper_lib.py", line 144, in vdb_read_grids_list
    raise RuntimeError(err_str)
RuntimeError: IoError: could not get size of file ..\..\..\..\..\..\..\..\

**Comment by bnagirniak** [comment]
Looks like it unable to read some of OpenVDB (.vdb) file which is used in scene. Can you please check that such file exists?

**Comment by pgedeon** [comment]
Fixed, the .vdb link was broken.
