### ISSUE TITLE
RPR 3.0.33 error enabling the addon in blender

### ISSUE THREAD

**Issue by NPDan87** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#233]
After the module is installed correctly i get this message:
Modules Installed (rprblender) from '/home/npdan/Downloads/RadeonProRenderForBlender_3.0.33_Ubuntu20.zip' into '/home/npdan/.config/blender/2.83/scripts/addons'
2021-03-23 21:48:53,368 INFO rpr.engine.init [140085369024576]:  RPR Core version: 2.2.0 build 0x575ce2d5
2021-03-23 21:48:53,388 INFO rpr.engine.init [140085369024576]:  Image Filters version 1.6.1 build 0xe4886697
2021-03-23 21:48:53,391 INFO rpr.default [140085369024576]:  rprsdk_bin_path: /home/npdan/.config/blender/2.83/scripts/addons/rprblender
Traceback (most recent call last):
  File "/home/npdan/Downloads/stable/blender-2.83.13-linux64/2.83/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/npdan/.config/blender/2.83/scripts/addons/rprblender/__init__.py", line 51, in <module>
    from .engine.viewport_engine import ViewportEngine
  File "/home/npdan/.config/blender/2.83/scripts/addons/rprblender/engine/viewport_engine.py", line 31, in <module>
    from rprblender.utils import gl
  File "/home/npdan/.config/blender/2.83/scripts/addons/rprblender/utils/gl.py", line 25, in <module>
    gl = cdll.LoadLibrary('libGL.so')
  File "/home/npdan/Downloads/stable/blender-2.83.13-linux64/2.83/python/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/home/npdan/Downloads/stable/blender-2.83.13-linux64/2.83/python/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libGL.so: cannot open shared object file: No such file or directory

Running Linux, Kubuntu, 20.04 LTS on blender 2.83.13 LTS with only OpenCL installed -headless via amd-gpu-pro driver 20.50, Mesa 20.2.6, 5.8.0-45-generic kernel

**Comment by bsavery** [comment]
Please see #203 about missing libGL
