### ISSUE TITLE
"NameError: name 'rprsdk_bin_path' is not defined" on macOS 11.2.2, Blender 2.93.0 Alpha

### ISSUE THREAD

**Issue by seanr** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#253]
Can't enable ProRender at all in 2.93 on my Mac - this was the nightly from two weeks or so ago. It throws the following, but with no additional information that I can find:

```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/seanr/Library/Application Support/Blender/2.93/scripts/addons/rprblender/__init__.py", line 39, in <module>
    from .engine.engine import Engine
  File "/Users/seanr/Library/Application Support/Blender/2.93/scripts/addons/rprblender/engine/__init__.py", line 140, in <module>
    register_plugins()
  File "/Users/seanr/Library/Application Support/Blender/2.93/scripts/addons/rprblender/engine/__init__.py", line 108, in register_plugins
    register_plugin(pyrpr.Context,
  File "/Users/seanr/Library/Application Support/Blender/2.93/scripts/addons/rprblender/engine/__init__.py", line 101, in register_plugin
    lib_path = rprsdk_bin_path / lib_name
NameError: name 'rprsdk_bin_path' is not defined
```

It does enable in 2.92.

**Comment by seanr** [comment]
One thing I noticed, incidentally, is that 2.93 uses Python 3.9 instead of 3.7 - I wonder if that's got anything to do with it?

**Comment by seanr** [comment]
I think I pasted the wrong error before, this is the actual one I'm getting in Blender (not Bforartists):

```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/seanr/Library/Application Support/Blender/2.93/scripts/addons/rprblender/__init__.py", line 39, in <module>
    from .engine.engine import Engine
  File "/Users/seanr/Library/Application Support/Blender/2.93/scripts/addons/rprblender/engine/__init__.py", line 140, in <module>
    register_plugins()
  File "/Users/seanr/Library/Application Support/Blender/2.93/scripts/addons/rprblender/engine/__init__.py", line 108, in register_plugins
    register_plugin(pyrpr.Context,
  File "/Users/seanr/Library/Application Support/Blender/2.93/scripts/addons/rprblender/engine/__init__.py", line 101, in register_plugin
    lib_path = rprsdk_bin_path / lib_name
NameError: name 'rprsdk_bin_path' is not defined
```

**Comment by bsavery** [comment]
Hi Sean, we do in fact not support Blender 2.93 yet because of the Python 3.9 issue.  See issue #213 . I'm going to close this issue as duplicate to that but please subscribe to the other issue for updates.  Thanks!
