### ISSUE TITLE
Render error after applying denoise part

### ISSUE THREAD

**Issue by yashwanth2804** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#266]
system info
cpu ryzen 7 2700
gpu rx 580

![image](https://user-images.githubusercontent.com/8038593/117763785-015a8b80-b249-11eb-8004-07aa1d17a845.png)

![image](https://user-images.githubusercontent.com/8038593/117530762-99176a00-affc-11eb-86ed-6359f557addf.png)

![image](https://user-images.githubusercontent.com/8038593/117530852-0925f000-affd-11eb-82fe-4c95602da840.png)

**Comment by relubwu** [comment]
Can reproduce this error on macOS 11.2.3 running Blender 2.91.0 with Radeon Pro 5500M as well. Error occurs after sampling iterations are done, as soon as "denoising..." prompt shows. 

Full error message: 

`[ERROR@RIF]: RIF_ERROR_OUT_OF_VIDEO_MEMORY at file /Users/admin/JN/WS/RadeonProImageProcessor_Build/src/AIFilters.cpp line 620
2021-05-10 22:28:58,841 ERROR rpr.viewport_engine [123145590587392]:  RIF call ContextExecuteCommandQueue(<pyrprimagefilters.Context object at 0x12f7fc950>, <pyrprimagefilters.CommandQueue object at 0x12f7fc510>, <cdata 'void *' NULL>, <cdata 'void *' NULL>, <cdata 'void *' NULL>) returned error code <-3> with error message: '' EXCEPTION: Traceback (most recent call last):
  File "/Users/redacted/Library/Application Support/Blender/2.91/scripts/addons/rprblender/engine/viewport_engine.py", line 449, in _do_sync_render
    self._do_render()
  File "/Users/redacted/Library/Application Support/Blender/2.91/scripts/addons/rprblender/engine/viewport_engine_2.py", line 242, in _do_render
    self.upscale_filter.run()
  File "/Users/redacted/Library/Application Support/Blender/2.91/scripts/addons/rprblender/engine/image_filter.py", line 109, in run
    self.command_queue.execute()
  File "/Users/redacted/Library/Application Support/Blender/2.91/scripts/addons/rprblender/pyrprimagefilters.py", line 366, in execute
    ContextExecuteCommandQueue(self.context, self, ffi.NULL, ffi.NULL, ffi.NULL)
  File "/Users/redacted/Library/Application Support/Blender/2.91/scripts/addons/rprblender/pyrpr.py", line 78, in wrapped
    raise CoreError(status, f.__name__, argv, module_name)
pyrpr.CoreError: RIF call ContextExecuteCommandQueue(<pyrprimagefilters.Context object at 0x12f7fc950>, <pyrprimagefilters.CommandQueue object at 0x12f7fc510>, <cdata 'void *' NULL>, <cdata 'void *' NULL>, <cdata 'void *' NULL>) returned error code <-3> with error message: ''

ERROR:rpr.viewport_engine:RIF call ContextExecuteCommandQueue(<pyrprimagefilters.Context object at 0x12f7fc950>, <pyrprimagefilters.CommandQueue object at 0x12f7fc510>, <cdata 'void *' NULL>, <cdata 'void *' NULL>, <cdata 'void *' NULL>) returned error code <-3> with error message: '' EXCEPTION: Traceback (most recent call last):
  File "/Users/redacted/Library/Application Support/Blender/2.91/scripts/addons/rprblender/engine/viewport_engine.py", line 449, in _do_sync_render
    self._do_render()
  File "/Users/redacted/Library/Application Support/Blender/2.91/scripts/addons/rprblender/engine/viewport_engine_2.py", line 242, in _do_render
    self.upscale_filter.run()
  File "/Users/redacted/Library/Application Support/Blender/2.91/scripts/addons/rprblender/engine/image_filter.py", line 109, in run
    self.command_queue.execute()
  File "/Users/redacted/Library/Application Support/Blender/2.91/scripts/addons/rprblender/pyrprimagefilters.py", line 366, in execute
    ContextExecuteCommandQueue(self.context, self, ffi.NULL, ffi.NULL, ffi.NULL)
  File "/Users/redacted/Library/Application Support/Blender/2.91/scripts/addons/rprblender/pyrpr.py", line 78, in wrapped
    raise CoreError(status, f.__name__, argv, module_name)
pyrpr.CoreError: RIF call ContextExecuteCommandQueue(<pyrprimagefilters.Context object at 0x12f7fc950>, <pyrprimagefilters.CommandQueue object at 0x12f7fc510>, <cdata 'void *' NULL>, <cdata 'void *' NULL>, <cdata 'void *' NULL>) returned error code <-3> with error message: ''
`

**Comment by yashwanth2804** [comment]
@relubwu I am using Win10 by the way

**Comment by bsavery** [comment]
Please disable the "viewport denoising and upsampling" option

**Comment by relubwu** [comment]
> Please disable the "viewport denoising and upsampling" option

So, should this be considered a known bug?

**Comment by bsavery** [comment]
On macOS yes.  The latest beta builds have it disabled on Mac.

**Comment by relubwu** [comment]
> On macOS yes. The latest beta builds have it disabled on Mac.

Copy that, thanks! How about @yashwanth2804 ?

**Comment by yashwanth2804** [comment]
> Please disable the "viewport denoising and upsampling" option

Can you please tell me where it is, I am new to blender sorry.

**Comment by relubwu** [comment]
> > Please disable the "viewport denoising and upsampling" option
> 
> Can you please tell me where it is, I am new to blender sorry.

Under the Properties panel (bottom right) -> Render Properties (camera icon) -> Sampling -> Viewport & Preview Sampling -> uncheck Viewport Denoising and Upscale

**Comment by yashwanth2804** [comment]
I am not getting that issue any more , may be i can close this issue, Thank you community for the effort , Cycles always crashes and causes BSOD many times atleast using this pulgin is a saviuor , but color acuray and noise , appealing I like Cycles better. There is still a need to  improve . ❤️  🤟
