### ISSUE TITLE
When enabling addon there is an error and it's not enabling itself.

### ISSUE THREAD

**Issue by ArekKubinski** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#293]
Every issue should include 3 things:
1.  System setup (GPU, CPU, OS version, Blender version)
GPU: Radeon RX 570
CPU: AMD Ryzen 7 3800XT
OS version: Windows 10 64bit
Blender version: 2.93.0 
2.  **Most ideally** a .blend scene to reproduce this simply.  **SCREENSHOTS OR RENDERS ARE NOT A SCENE FILE**
empty scene
3.  What the expected behavior or effect is.  If possible include the error message.  
I wand to add this addon but every time i try i doesen't matter if i'm using clean blender i can never enable this addon succesfully. My os is freshly formatted instalation so i don't know why this happens. I installed this in accordance to instruction.

You can get more information on the error message by opening Window -> Show System Console from blender and copying that text here.  On MacOS launch Blender from the Terminal.

`  File "C:\Users\pejpe\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\rprblender\engine\__init__.py", line 41, in pyrpr_init
    pyrpr.init(logging.Log(tag='core'), rprsdk_bin_path=rprsdk_bin_path)
  File "C:\Users\pejpe\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\rprblender\pyrpr.py", line 147, in init
    assert False
AssertionError

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\pejpe\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\rprblender\__init__.py", line 39, in <module>
    from .engine.engine import Engine
  File "C:\Users\pejpe\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\rprblender\engine\__init__.py", line 87, in <module>
    assert pyrpr_init(bindings_import_path, rprsdk_bin_path)
AssertionError

Traceback (most recent call last):
  File "C:\Users\pejpe\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\rprblender\utils\helper_lib.py", line 65, in init
    lib = ctypes.cdll.LoadLibrary(str(lib_path))
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] Nie można odnaleźć określonej procedury

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\pejpe\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\rprblender\__init__.py", line 39, in <module>
    from .engine.engine import Engine
  File "C:\Users\pejpe\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\rprblender\engine\__init__.py", line 137, in <module>
    import rprblender.utils.helper_lib
  File "C:\Users\pejpe\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\rprblender\utils\helper_lib.py", line 183, in <module>
    init()
  File "C:\Users\pejpe\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\rprblender\utils\helper_lib.py", line 70, in init
    f"rif {rif_ver_str(True)}",
  File "C:\Users\pejpe\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\rprblender\utils\__init__.py", line 74, in rif_ver_str
    import pyrprimagefilters
ModuleNotFoundError: No module named 'pyrprimagefilters'`

**Comment by subevilx** [comment]
Download Blender from --> https://download.blender.org/release/Blender2.92/ 
As prorender isnt supported for 2.93

**Comment by ArekKubinski** [comment]
> Download Blender from --> https://download.blender.org/release/Blender2.92/
> As prorender isnt supported for 2.93

Yeah my bad, sorry for this, it working properly now
