### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by max1mvs** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#349]
## Issue

When trying to enable the plugin, I get the following error:

```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/massimo/Library/Application Support/Blender/2.93/scripts/addons/rprblender/__init__.py", line 39, in <module>
    from .engine.engine import Engine
  File "/Users/massimo/Library/Application Support/Blender/2.93/scripts/addons/rprblender/engine/__init__.py", line 25, in <module>
    if utils.IS_DEBUG_MODE:
AttributeError: module 'rprblender.utils' has no attribute 'IS_DEBUG_MODE'
```

## Steps to Reproduce

1. Install the latest plugin (version 3.2.2)
2. (Try to) enable it under Preferences -> Add-ons

## System Setup (Environment)

macOS 11.5.2

CPU: 2,3 GHz Quad-Core Intel Core i7
GPU: Intel Iris Plus Graphics
eGPU: Radeon RX Vega 64

Blender version: 2.93.2

**Comment by etx** [comment]
Same issue here. Blender 2.93.0 on MacOS but I'm using the latest tagged build 3.2.16. It was also doing this for build 3.2.2 which is why I tried out the latest build.

```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/etx/Library/Application Support/Blender/2.93/scripts/addons/rprblender/__init__.py", line 39, in <module>
    from .engine.engine import Engine
  File "/Users/etx/Library/Application Support/Blender/2.93/scripts/addons/rprblender/engine/__init__.py", line 25, in <module>
    if utils.IS_DEBUG_MODE:
AttributeError: module 'rprblender.utils' has no attribute 'IS_DEBUG_MODE'

```

**Comment by Aliprandini** [comment]
Try to DELETE "modules" folder by the path "/Users/<user name>/Library/Application Support/Blender/2.93/scripts"

**Comment by etx** [comment]
I didn't find a `modules` folder in there, but I deleted scripts/addons/rprblender and then I reinstalled the zip from blender. Not it's loading up fine. Thank you!

**Comment by max1mvs** [comment]
> I didn't find a `modules` folder in there, but I deleted `scripts/addons/rprblender` and then I reinstalled the zip from Blender. Now it's loading up fine. Thank you!

That exact sequence did the trick for me as well. Thank you @etx & @Aliprandini !
