### ISSUE TITLE
Error enable add-on AttributeError: module 'rprblender.utils' has no attribute 'IS_DEBUG_MODE'

### ISSUE THREAD

**Issue by Kishinskiy** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#409]
## System Setup (Environment)

Blender 2.9

## Detailed Description

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/kishinskiy/Library/Application Support/Blender/2.93/scripts/addons/rprblender/__init__.py", line 39, in <module>
    from .engine.engine import Engine
  File "/Users/kishinskiy/Library/Application Support/Blender/2.93/scripts/addons/rprblender/engine/__init__.py", line 25, in <module>
    if utils.IS_DEBUG_MODE:
AttributeError: module 'rprblender.utils' has no attribute 'IS_DEBUG_MODE'

**Comment by DagerD** [comment]
Try to test our latest release.
