### ISSUE TITLE
" Object has no attribute "Cycles_visibility".

### ISSUE THREAD

**Issue by wobat** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#415]
using win10 Blender 3.0 with AMD Fury x 

installing Radeonpro driver 3.3 .

Cycle is working
Eevee is working.
Radeon Pro get error " Object has no attribute "Cycles_visibility".

What can i do? or programming error?

sincerely
wobat

**Comment by bsavery** [comment]
You didn't include a file.  Do you have Cycles enabled?

**Comment by mimoguz** [comment]
I have the same issue. Radeon RX 570, ProRender 3.3.0. Cycles is enabled and working.

[A sample scene if it's needed.](https://1drv.ms/u/s!Ahsda0rPt-lgnvI_wpdFr2p0vmJdCg?e=c0cIQ9). But it's just the default scene.

Error details:

    2021-12-09 19:10:05,306 ERROR rpr.viewport_engine [17816]:  'Object' object has no attribute 'cycles_visibility' EXCEPTION: Traceback (most recent call last):
    File "C:\Path\To\Blender\3.0\scripts\addons\rprblender\engine\viewport_engine.py", line 458, in _do_sync_render
        self._do_sync(depsgraph)
    File "C:\Path\To\Blender\3.0\scripts\addons\rprblender\engine\viewport_engine.py", line 261, in _do_sync
        object.sync(self.rpr_context, obj,
    File "C:\Path\To\Blender\3.0\scripts\addons\rprblender\export\object.py", line 44, in sync
        mesh.sync(rpr_context, obj, **kwargs)
    File "C:\Path\To\Blender\3.0\scripts\addons\rprblender\export\mesh.py", line 379, in sync
        sync_visibility(rpr_context, obj, rpr_shape, indirect_only=indirect_only)
    File "C:\Path\To\Blender\3.0\scripts\addons\rprblender\export\mesh.py", line 301, in sync_visibility
        export_visibility(obj, rpr_shape, indirect_only)
    File "C:\Path\To\Blender\3.0\scripts\addons\rprblender\export\mesh.py", line 276, in export_visibility
        cycles_visibility = obj.cycles_visibility
    AttributeError: 'Object' object has no attribute 'cycles_visibility'

**Comment by bsavery** [comment]
#406  actually fixed this.  You can get the build here:  https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.3.9
