### ISSUE TITLE
"Object has no attribute 'Cycles_visibility'"still exists in Macos

### ISSUE THREAD

**Issue by TerenceNg03** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#423]
Object has no attribute "Cycles_visibility" still exists in latest macos release.

## Issue

The issue is the same as #415 . However, this is still not yet fixed in macos release.

Log file shows this issue happens in `mesh.py`.
```
2021-12-11 23:09:17,277 rpr.init [123145566965760]: ERROR 'Object' object has no attribute 'cycles_visibility' EXCEPTION: Traceback (most recent call last):
  File "/Users/terenceng/Library/Application Support/Blender/3.0/scripts/addons/rprblender/__init__.py", line 123, in update
    self.engine.sync(depsgraph)
  File "/Users/terenceng/Library/Application Support/Blender/3.0/scripts/addons/rprblender/engine/preview_engine.py", line 107, in sync
    object.sync(self.rpr_context, obj)
  File "/Users/terenceng/Library/Application Support/Blender/3.0/scripts/addons/rprblender/export/object.py", line 44, in sync
    mesh.sync(rpr_context, obj, **kwargs)
  File "/Users/terenceng/Library/Application Support/Blender/3.0/scripts/addons/rprblender/export/mesh.py", line 379, in sync
    sync_visibility(rpr_context, obj, rpr_shape, indirect_only=indirect_only)
  File "/Users/terenceng/Library/Application Support/Blender/3.0/scripts/addons/rprblender/export/mesh.py", line 301, in sync_visibility
    export_visibility(obj, rpr_shape, indirect_only)
  File "/Users/terenceng/Library/Application Support/Blender/3.0/scripts/addons/rprblender/export/mesh.py", line 276, in export_visibility
    cycles_visibility = obj.cycles_visibility
AttributeError: 'Object' object has no attribute 'cycles_visibility'
```

## System Setup (Environment)

Macos 12.0.1

Release v3.3.11

Blender 3.0.0

GPU rendering

## Detailed Description

After some investigation , I think here is what caused the issue.

This issue is resolved in #406 by adding a test for blender version in `mesh.py`.
However, this file is not updated in the Release v3.3.11 macos build.
Here is my `mesh.py` downloaded from that release.
```
def export_visibility(obj, rpr_shape, indirect_only):
    """ Exports visibility settings """
    cycles_visibility = obj.cycles_visibility

    camera_visibility = cycles_visibility.camera and not indirect_only

    rpr_shape.set_visibility_primary_only(camera_visibility)
    rpr_shape.set_visibility_ex("visible.reflection", cycles_visibility.glossy)
    rpr_shape.set_visibility_ex("visible.reflection.glossy", cycles_visibility.glossy)
    rpr_shape.set_visibility_ex("visible.refraction", cycles_visibility.transmission)
    rpr_shape.set_visibility_ex("visible.refraction.glossy", cycles_visibility.transmission)
    rpr_shape.set_visibility_ex("visible.diffuse", cycles_visibility.diffuse)
    rpr_shape.set_shadow(cycles_visibility.shadow)

    obj.rpr.set_catchers(rpr_shape)
```
It probably should be like
```
def export_visibility(obj, rpr_shape, indirect_only):
    """ Exports visibility settings """
    if BLENDER_VERSION >= '3.0':
        rpr_shape.set_visibility_primary_only(obj.visible_camera and not indirect_only)
        rpr_shape.set_visibility_ex("visible.reflection", obj.visible_glossy)
        rpr_shape.set_visibility_ex("visible.reflection.glossy", obj.visible_glossy)
        rpr_shape.set_visibility_ex("visible.refraction", obj.visible_transmission)
        rpr_shape.set_visibility_ex("visible.refraction.glossy", obj.visible_transmission)
        rpr_shape.set_visibility_ex("visible.diffuse", obj.visible_diffuse)
        rpr_shape.set_shadow(obj.visible_shadow)

    else:
        visibility = obj.cycles_visibility
        rpr_shape.set_visibility_primary_only(visibility.camera and not indirect_only)
        rpr_shape.set_visibility_ex("visible.reflection", visibility.glossy)
        rpr_shape.set_visibility_ex("visible.reflection.glossy", visibility.glossy)
        rpr_shape.set_visibility_ex("visible.refraction", visibility.transmission)
        rpr_shape.set_visibility_ex("visible.refraction.glossy", visibility.transmission)
        rpr_shape.set_visibility_ex("visible.diffuse", visibility.diffuse)
        rpr_shape.set_shadow(visibility.shadow)

    obj.rpr.set_catchers(rpr_shape)
```

**Comment by bsavery** [comment]
I just downloaded the release 3.3.11 and it does seem to have the correct code.  Is it possible you have an older version opened?

**Comment by TerenceNg03** [comment]
It turns out that I am using v3.3.0. I will close this issue.
