### ISSUE TITLE
Install instructions not working on fresh linux install -> Activation Errors

### ISSUE THREAD

**Issue by poisenbery** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#428]
I have tested on 2 distrubutions of linux [PopOS and Ubuntu, latest LTR for both].
I've checked compatible equipment and mine is compatible.
Upon trying to activate the plugin, per the install instructions, I am met with an error:

```
Traceback (most recent call last):
  File "/snap/blender/1237/3.0/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/poisenbery/.config/blender/3.0/scripts/addons/rprblender/__init__.py", line 51, in <module>
    from .engine.viewport_engine import ViewportEngine
  File "/home/poisenbery/.config/blender/3.0/scripts/addons/rprblender/engine/viewport_engine.py", line 33, in <module>
    from rprblender.utils import gl
  File "/home/poisenbery/.config/blender/3.0/scripts/addons/rprblender/utils/gl.py", line 25, in <module>
    gl = cdll.LoadLibrary('libGL.so')
  File "/snap/blender/1237/3.0/python/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/snap/blender/1237/3.0/python/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libGL.so: cannot open shared object file: No such file or directory
```

It seems like there are some prerequisites that are not mentioned anywhere in the install instructions. I tried googling "libGL.so" and found a page saying I needed to install libglx-mesa0

```
sudo apt update
sudo apt install libglx-mesa0
```

But even after this, I am still getting the same error.

I have googled the issue and I am not the only one who has had this problem. I was playing a game of "install the missing package" last night and managed to get up to a package named "six" before it stopped working entirely.

**Comment by poisenbery** [comment]
Seems I did not have open CL installed.

New user mistake. It was listed on the  requirements and I assumed I had it.

For thos with the issue, use this command:

```
sudo apt update
sudo apt install ocl-icd-opencl-dev
```

Activated without issues after I ran this.
