### ISSUE TITLE
Cannot build the addon

### ISSUE THREAD

**Issue by jiriks74** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#433]
## Issue
I get this error while running `./build.sh`
<details>

```
Traceback (most recent call last):
File "/home/jirka/Programs/Projects/RadeonProRenderBlenderAddon/src/bindings/pyrpr/rpr.py", line 155, in <module>
export('pyrprwrapapi.json', [], 'rprwrap.h',
File "/home/jirka/Programs/Projects/RadeonProRenderBlenderAddon/src/bindings/pyrpr/rpr.py", line 109, in export
subprocess.check_call(cmd)
File "/usr/lib/python3.9/subprocess.py", line 368, in check_call
retcode = call(*popenargs, **kwargs)
File "/usr/lib/python3.9/subprocess.py", line 349, in call
with Popen(*popenargs, **kwargs) as p:
File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'patchelf'
Traceback (most recent call last):
File "/home/jirka/Programs/Projects/RadeonProRenderBlenderAddon/build.py", line 40, in <module>
subprocess.check_call([sys.executable, 'rpr.py'])
File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3.9', 'rpr.py']' returned non-zero exit status 1.
```
</details>

## Steps to Reproduce
- Clone the repository `git clone --recursive git@github.com:GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon.git`
- Install cffi (`python3.7 -m pip install cffi && python3.9 -m pip install cffi`)
- Run `./build.sh`

**Comment by DagerD** [comment]
Hello.

> FileNotFoundError: [Errno 2] No such file or directory: 'patchelf'

Please install patchelf for your python and try again.

**Comment by jiriks74** [comment]
Built successfully
