### ISSUE TITLE
The 3.3.21 Windows version reports errors while running on blender3.1 production

### ISSUE THREAD

**Issue by mayloglog** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#467]
error message：
Traceback (most recent call last):
  File "J:\blender\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\may\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\__init__.py", line 39, in <module>
    from .engine.engine import Engine
  File "C:\Users\may\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\engine\__init__.py", line 55, in <module>
    pyrpr.init(rpr_lib_dir, logging.Log(tag='core'), config.pyrpr_log_calls)
  File "C:\Users\may\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\pyrpr.py", line 110, in init
    import __rpr
ModuleNotFoundError: No module named '__rpr'

**Comment by ARozghon** [comment]
Blender 3.1 support is now in progress, will be available soon. In Blender 3.1 was changed Python version and the current RPR not working correctly for now. Thank you

**Comment by bsavery** [comment]
Please try:  https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.3.26
