### ISSUE TITLE
Can't activate addon after installation

### ISSUE THREAD

**Issue by StnVslv** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#480]
Hi Guys!
Just after installing addon tryin to activate it and got error:

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.1/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/stn/Library/Application Support/Blender/3.1/scripts/addons/rprblender/__init__.py", line 39, in <module>
    from .engine.engine import Engine
  File "/Users/stn/Library/Application Support/Blender/3.1/scripts/addons/rprblender/engine/__init__.py", line 55, in <module>
    pyrpr.init(rpr_lib_dir, logging.Log(tag='core'), config.pyrpr_log_calls)
  File "/Users/stn/Library/Application Support/Blender/3.1/scripts/addons/rprblender/pyrpr.py", line 110, in init
    import __rpr
  File "/Users/stn/Library/Application Support/Blender/3.1/scripts/addons/rprblender/__rpr.py", line 2, in <module>
    import _cffi_backend
ModuleNotFoundError: No module named '_cffi_backend'

How can i solve it?
i've tried both win and mac on my pc.

Blender 3.1.2 
ProRender for Blender 3.3.15

macos 11.6.5 (or win 11 same error)

cpu i5 11600k 
gpu rx5700xt (latest driver from amd web page)

thx

**Comment by bsavery** [comment]
Can you take a look at the issue https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/86

You want to be using RPR 3.3.26 for blender 3.1 https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.3.26

**Comment by StnVslv** [comment]
> Can you take a look at the issue #86
> 
> You want to be using RPR 3.3.26 for blender 3.1 https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.3.26

it works! thanks a lot!
