### ISSUE TITLE
Error enabling addon: ModuleNotFoundError: No module named '__rpr'

### ISSUE THREAD

**Issue by NikorinMP** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#485]
System information:
GPU: AMD Radeon RX Vega 11
CPU: AMD Ryzen 5 3400g
OS: Windows 10 Pro
Blender version: 3.1.2

Procedure:
Installed addon from Blender. 
- Create new blender file.
- Edit > Preferences > Addons > Install.
- Left clicked on the tick box to enable it.

Expected:
Addon being enabled and ready to use.

Result:
Error:
Traceback (most recent call last):
  File "D:\Archivos\Juegos\Steam\steamapps\common\Blender\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Nicolas\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\__init__.py", line 39, in <module>
    from .engine.engine import Engine
  File "C:\Users\Nicolas\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\engine\__init__.py", line 55, in <module>
    pyrpr.init(rpr_lib_dir, logging.Log(tag='core'), config.pyrpr_log_calls)
  File "C:\Users\Nicolas\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\pyrpr.py", line 110, in init
    import __rpr
ModuleNotFoundError: No module named '__rpr'

Hi, I'm new to GitHub. I hope the format is correct.

This error is driving me crazy. I know 0 Python. 
There was a similar post already with a command to input somewhere, but it didn't expand on it.
(Here's the most similar post I found if that helps: https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/354)

Thanks for your time.

![Screenshot_91](https://user-images.githubusercontent.com/103891262/163720611-df0b47e0-33f1-4c2e-8a87-21b4a71dc399.png)

**Comment by bsavery** [comment]
Try this build. https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.3.29

**Comment by NikorinMP** [comment]
That solved the issue I had!
Thank you!!
