### ISSUE TITLE
Installation Error "Unknown Location"

### ISSUE THREAD

**Issue by Jamarm** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#490]
System:
OS: Windows 10 Pro
CPU: AMD Ryzen 5 2600 Six-Core Processor 3.40 GHz
GPU:  Radeon RX 580 Series | Driver - AMD Radeon 22.1.2
Blender Version: 3.1.0
 
Procedure:
Open Blender > Edit > Preferences > Addons > Install > Select .zip file "RadeonProRenderForBlender_3.3.15_Windows"
 
Result:
I was unable to tick the box, that was my first error. Which I screenshot. After rebooting Blender. I tried again however I was unable to. I then tried to uninstall the addon upon clicking "Remove" and I received my second error. Preventing me from uninstalling.
 
Error:
 
(Screenshot)
![unknown_2022 04 21-09 48](https://user-images.githubusercontent.com/47537138/164483673-fdcc885d-e6a3-4146-8686-829c16b861fe.png)
 
(Error Text)
bpy.data.window_managers["WinMan"].addon_search = "amd" Python: Traceback (most recent call last): File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\startup\bl_operators\userpref.py", line 782, in execute shutil.rmtree(path) File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\shutil.py", line 739, in rmtree return _rmtree_unsafe(path, onerror) File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\shutil.py", line 617, in _rmtree_unsafe onerror(os.unlink, fullname, sys.exc_info()) File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\shutil.py", line 615, in _rmtree_unsafe os.unlink(fullname) PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Jamar\\AppData\\Roaming\\Blender Foundation\\Blender\\3.1\\scripts\\addons\\rprblender\\rprblender.log' location: <unknown location>:-1 Python: Traceback (most recent call last): File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\startup\bl_operators\userpref.py", line 782, in execute shutil.rmtree(path) File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\shutil.py", line 739, in rmtree return _rmtree_unsafe(path, onerror) File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\shutil.py", line 617, in _rmtree_unsafe onerror(os.unlink, fullname, sys.exc_info()) File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\shutil.py", line 615, in _rmtree_unsafe os.unlink(fullname) PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Jamar\\AppData\\Roaming\\Blender Foundation\\Blender\\3.1\\scripts\\addons\\rprblender\\rprblender.log' location: <unknown location>:-1
 
After this second attempt, I restarted my PC and rebooted Blender and although I still couldn’t tick the box, I was able to uninstall the addon unlike before.
 
Hopefully, I successfully documented the issue clearly and this can be resolved, Thank you in advance.

**Comment by bsavery** [comment]
To use the plugin in blender 3.1 you need the latest build from here:  https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases

(not 3.3.15 build you are using). See this issue:  https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/480 Basically Blender changed the python version.  


On the "removing the add-on issue".  This is a long standing blender bug.  Add-ons that call other DLL's (like RPR) need a 2 step issue to remove. 
1.  Disable add-on (or in you case don't enable it)
2.  Restart blender and then remove without enabling.  

The problem is that Blender doesn't release DLL's that are loaded even when unchecking the box.  Here is the blender bug causing this that is not yet fixed.  https://developer.blender.org/T77837

**Comment by Jamarm** [comment]
Thank you, it worked. Will I often need to install the latest build?
