### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by DokimosNek** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#495]
## Issue
Hello everyone, I downloaded Radeon ProRender for Blender 3.3.15 zip, installed it to Blenders Add-ons, then i clicked to enable it and the following error pops:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\jimsk\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\__init__.py", line 39, in <module>
    from .engine.engine import Engine
ModuleNotFoundError: No module named 'rprblender.engine'

## System Setup (Environment)
 OS version : 19044.1645
rx580 8gb, 
AMD Ryzen 3 3100 4-Core Processor 3.60 GHz -->
Blender 3.1

**Comment by VascoPi** [comment]
Hi, Blender 3.3.15 doesn't support Blender 3.1.
The latest [weekly build](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.3.30) should work well.

**Comment by DokimosNek** [comment]
> Hi, Blender 3.3.15 doesn't support Blender 3.1. The latest [weekly build](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.3.30) should work well.

This worked for my issue. Thank you very much
