### ISSUE TITLE
blender 3.1 not working with the addon

### ISSUE THREAD

**Issue by MaxiKitti** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#503]
im getting this error in blender 3.1 when tryiing to enable the add-on
Traceback (most recent call last):
  File "G:\blender-3.1.0-candidate+v31.45079b169dc5-windows.amd64-release\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Max\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\__init__.py", line 39, in <module>
    from .engine.engine import Engine
  File "C:\Users\Max\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\engine\__init__.py", line 55, in <module>
    pyrpr.init(rpr_lib_dir, logging.Log(tag='core'), config.pyrpr_log_calls)
  File "C:\Users\Max\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\pyrpr.py", line 110, in init
    import __rpr
ModuleNotFoundError: No module named '__rpr'

**Comment by bsavery** [comment]
Install the latest version or Blender 3.1. https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/495

**Comment by MaxiKitti** [comment]
i reinstalled my blender 3.1 and im using the latest version of the addon and i still get the error

**Comment by bsavery** [comment]
Which version of the add-on do you have?

**Comment by bsavery** [comment]
What does it say the version of the add-on is in "Help / About" section of the settings.  I'd be willing to bet you still have the older version, this user had the same issue and installing the latest fixed it: 

https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/485

<img width="366" alt="Screen Shot 2022-05-12 at 8 31 10 AM" src="https://user-images.githubusercontent.com/1892220/168112884-1b6b1c05-704c-4874-8579-dd3d48619718.png">

**Comment by bsavery** [comment]
If yours says 3.3.15 you still have the old version

**Comment by nisimjoseph** [comment]
still getting the error:

Traceback (most recent call last):
File "/Applications/Blender 3.2.app/Contents/Resources/3.2/scripts/modules/addon_utils.py", line 335, in enable
mod =_import_ (module name)
File"/Users/nisim.j/Library/ApplicationSupport/Blender/3.2/scripts/addons/norblender/init.py",line39,in<module>
from .engine engine import Engine
File"/Users/nisim./Library/Application Support/Blender/3.2/scripts/addons/rprblender/engine/
init .py", line 55, in <module>
pyrpr.init(ror_lib_dir, logging.Log(tag='core'), config.pyrpr_log_calls)
File "/Users/nisim.i/Library/Application Support/Blender/3.2/scripts/addons/rorblender/pyror.py",line 110, in init
import nor
File "/Users/nisim.j/Library/Application Support/Blender/3.2/scripts/addons/prblender/ rpr.py", line 2, in <module>
import cffi backend
ModuleNotFoundError: No module named cffi backend'

**Comment by nisimjoseph** [comment]
same error on Blender 3.2 Beta

**Comment by bsavery** [comment]
Please reopen if you see the same issue with released 3.2
