### ISSUE TITLE
Error while enabling addon on 3.2 release

### ISSUE THREAD

**Issue by KaranveerSinghYT** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#524]
## Issue
Throws the following error while enabling addon (installation of addon completes successfully):

Traceback (most recent call last):
  File "D:\Blender\blender-3.2.0-windows-x64\3.2\scripts\modules\addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "C:\Users\Gamination\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\rprblender\__init__.py", line 40, in <module>
    from .engine.engine import Engine
  File "C:\Users\Gamination\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\rprblender\engine\__init__.py", line 55, in <module>
    pyrpr.init(rpr_lib_dir, logging.Log(tag='core'), config.pyrpr_log_calls)
TypeError: init() takes from 1 to 2 positional arguments but 3 were given

## System Setup (Environment)
22H2 Windows 11
GPU: Radeon RX 5600M
CPU: Ryzen 4600H
Driver Version: 22.5.1
Blender Version: 3.2
GPU Rendering
Using 3.4.0 ProRender

**Comment by ARozghon** [comment]
hi, from which shop was installed Blender: Steam, Microsoft, or Blender official site?

**Comment by KaranveerSinghYT** [comment]
Blender official site

**Comment by bsavery** [comment]
This sounds like an issue where there was a leftover file from an old version of the plugin.

**Comment by woutverroens** [comment]
I have the same problem with blender 3.4:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\woutv\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\rprblender\__init__.py", line 40, in <module>
    from .engine.engine import Engine
  File "C:\Users\woutv\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\rprblender\engine\__init__.py", line 55, in <module>
    pyrpr.init(rpr_lib_dir, logging.Log(tag='core'), config.pyrpr_log_calls)
  File "C:\Users\woutv\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\rprblender\pyrpr.py", line 110, in init
    import __rpr
ImportError: DLL load failed while importing __rpr: Kan opgegeven procedure niet vinden.
