### ISSUE TITLE
Grey viewport in Interactive render mode

### ISSUE THREAD

**Issue by mobilex1122** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#568]
## Issue

When i switch to interactive mode it does not start. Instead of render i see gray (blender viewport color) viewport.

## Steps to Reproduce
1. Switch render quality to interactive
2. Switch to render view
3. See gray viewport and python error message in terminal.

## System Setup (Environment)
OS: Arch or windows 11 (I use both)
GPU: AMD Radeon RX 6600 (Latest driver on windows)
Blender version: 3.4
Mostly using GPU rendering

## Detailed Description

Error message: 
```
2022-12-20 17:54:04,707 ERROR rpr.init [140593525411840]:  RPR call ContextSetParameterByKeyString(<pyhybridpro.Context object at 0x7fde41ee7f70>, 369, b'/usr/bin/3.4/datafiles/colormanagement/config.ocio') returned error code <-18> with error message: '' EXCEPTION: Traceback (most recent call last):
  File "/home/mobilex/.config/blender/3.4/scripts/addons/rprblender/__init__.py", line 168, in view_update
    self.engine.sync(context, depsgraph)
  File "/home/mobilex/.config/blender/3.4/scripts/addons/rprblender/engine/viewport_engine_hybridpro.py", line 49, in sync
    super().sync(context, depsgraph)
  File "/home/mobilex/.config/blender/3.4/scripts/addons/rprblender/engine/viewport_engine.py", line 482, in sync
    scene.rpr.init_rpr_context(self.rpr_context, is_final_engine=False,
  File "/home/mobilex/.config/blender/3.4/scripts/addons/rprblender/properties/render.py", line 615, in init_rpr_context
    rpr_context.set_parameter(pyrpr.CONTEXT_OCIO_CONFIG_PATH, ocio_config_path)
  File "/home/mobilex/.config/blender/3.4/scripts/addons/rprblender/engine/context.py", line 534, in set_parameter
    self.context.set_parameter(key, param)
  File "/home/mobilex/.config/blender/3.4/scripts/addons/rprblender/pyhybridpro.py", line 46, in wrapper
    return function(*args, **kwargs)
  File "/home/mobilex/.config/blender/3.4/scripts/addons/rprblender/pyhybridpro.py", line 85, in set_parameter
    super().set_parameter(key, param)
  File "/home/mobilex/.config/blender/3.4/scripts/addons/rprblender/pyrpr.py", line 270, in set_parameter
    ContextSetParameterByKeyString(self, key, encode(param))
  File "/home/mobilex/.config/blender/3.4/scripts/addons/rprblender/pyrpr.py", line 74, in wrapped
    raise CoreError(status, f.__name__, argv, module_name)
pyrpr.CoreError: RPR call ContextSetParameterByKeyString(<pyhybridpro.Context object at 0x7fde41ee7f70>, 369, b'/usr/bin/3.4/datafiles/colormanagement/config.ocio') returned error code <-18> with error message: ''

```

**Comment by bsavery** [comment]
Which plugin version do you have?

**Comment by mrrms** [comment]
I'm getting the same grey (blender viewport) color when performing a viewport render.
- macOS Monterey 12.6.2
- RPRForBlenderMacos 3.5.0
- AMD Radeon 5700xt
- Blender 3.4
It performs a partial render, pauses for a moment, then the render is blocked by a whole bunch of grey squares.
![Screen Shot 2023-01-08 at 14 05 57](https://user-images.githubusercontent.com/36450865/211219045-07bb7d80-449e-48f2-bcdd-1a1d2fa32b82.png)

**Comment by mobilex1122** [comment]
> Which plugin version do you have?

The latest one

**Comment by mobilex1122** [comment]
> I'm getting the same grey (blender viewport) color when performing a viewport render.
> - macOS Monterey 12.6.2
> - RPRForBlenderMacos 3.5.0
> - AMD Radeon 5700xt
> - Blender 3.4
> It performs a partial render, pauses for a moment, then the render is covered by several grey squares.
> 
> 
> https://user-images.githubusercontent.com/36450865/211219337-6c11259b-6ca5-4fb1-b698-4beb27f7e04f.mov
> 
> 

I have little diferent one. for me it's gray form the start.

**Comment by kintuX** [comment]
Confirming. 
This issue is still
![RPR_VWPRTdns-bug](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/assets/61623470/1c183c4e-cfbe-4c53-9df7-8663420305a4)
 present in latest RPR dev. build v3.5.21
