### ISSUE TITLE
Traceback Error blender 3.4

### ISSUE THREAD

**Issue by woutverroens** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#572]
when wanting to add the add-on it gives back this error:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\woutv\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\rprblender\__init__.py", line 40, in <module>
    from .engine.engine import Engine
  File "C:\Users\woutv\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\rprblender\engine\__init__.py", line 55, in <module>
    pyrpr.init(rpr_lib_dir, logging.Log(tag='core'), config.pyrpr_log_calls)
  File "C:\Users\woutv\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\rprblender\pyrpr.py", line 110, in init
    import __rpr
ImportError: DLL load failed while importing __rpr: Kan opgegeven procedure niet vinden.

**Comment by woutverroens** [comment]
1. 
* System           Microsoft Windows 10 Home
* Processor	Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz, 1800 MHz, 4 core('s), 8 logische processor(s)
* GPU & VRAM AMD Radeon Pro WX3200 Graphics
* RAM              16 GB 2667 MHz DDR4 Memory

2. 
Blender 3.4 and plugin version: RadeonProRenderForBlender_3.5.0_Windows

3. 
dowload the .zip, folowed: https://radeon-pro.github.io/RadeonProRenderDocs/en/plugins/blender/installation.html 

4. 
Just any scene.

Thanks a lot in advance !!

**Comment by ARozghon** [comment]
thank you, will check and will try to reproduce

**Comment by ARozghon** [comment]
Hi, please, try the latest https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.5.2 
and I have suspicious about this GPU support in the latest version of the plugin. Thank you

**Comment by woutverroens** [comment]
This worked, thank you so much!!
