### ISSUE TITLE
RPR 3.5 GPU render fail - ERROR RIF call ImageMap RPR3.5

### ISSUE THREAD

**Issue by djtutorials** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#573]
**System setup (GPU, CPU, OS version, Blender version)**
RTX3090
AMD 3960x
Blender V 3.4.1
RPR 3.5.0 & 3.5.2
Windows 10
**A default file throws the error. Please let me know if you want this file.**

**Open default file, turn on RPR render engine, turn on GPU render, rendering throws error and sometimes crashes program and system. CPU render works okay.**

**Error Console Copy Start:**

ps.rml_plugin.dll
[MSG  @RIF]: Loaded RIF API version: 1.7.1.0xfdc139ba
[MSG  @RIF]: Loaded RIF API version: 1.7.1.0xfdc139ba
[MSG  @RIF]: Loaded RIF API version: 1.7.1.0xfdc139ba
[ERROR@RIF]: Image mapping failed at file C:\JN\WS\RadeonProImageProcessor_Build\src\Image.cpp line 601
2023-01-23 08:25:50,201 ERROR rpr.viewport_engine [12848]:  RIF call ImageMap(<pyrprimagefilters.Image object at 0x00000253A1E548B0>, 2, <cdata 'void * *' owning 8 bytes>) returned error code <-21> with error message: '' EXCEPTION: Traceback (most recent call last):
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\rprblender\engine\viewport_engine.py", line 458, in _do_sync_render
    self._do_render()
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\rprblender\engine\viewport_engine_2.py", line 237, in _do_render
    self.update_image_filter_inputs()
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\rprblender\engine\engine.py", line 296, in update_image_filter_inputs
    self.image_filter.update_input(input_id, data, tile_pos)
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\rprblender\engine\image_filter.py", line 82, in update_input
    self.inputs[input_id].set_data(data, pos)
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\rprblender\pyrprimagefilters.py", line 225, in set_data
    ImageMap(self, IMAGE_MAP_WRITE, mapped_data)
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\rprblender\pyrpr.py", line 74, in wrapped
    raise CoreError(status, f.__name__, argv, module_name)
pyrpr.CoreError: RIF call ImageMap(<pyrprimagefilters.Image object at 0x00000253A1E548B0>, 2, <cdata 'void * *' owning 8 bytes>) returned error code <-21> with error message: ''

**## Issue**
Should be rendering via GPU but instead it errors

**## Steps to Reproduce**
Open default file, turn on RPR render engine, turn on GPU render, rendering throws error and sometimes crashes program and system. CPU render works okay.

## System Setup (Environment)
Windows 10
GPU Driver: 528.24
Blender v 3.4.1
GPU Rendering

**Comment by djtutorials** [comment]
Hi there- just curious if anyone has been able to look into this. I am unable to render on GPU with 3.5.2 and 3.5.1 which was a recent weekly build will crash when I enable the addon. I was looking forward to doing more tutorials on this engine but unfortunately the addon simply does not work any more.

**Comment by ARozghon** [comment]
Hi, now the developer team is back to the active development of the RPR plugin. today will remind them to check your issues. Also, please try the latest driver and the latest or previous Nvidia driver, because Nvidia did something weird with their drivers and that provides a Final render engine error.
Thank you

**Comment by djtutorials** [comment]
Hi there- thanks for the response. I just installed the latest NVIDIA studio driver this AM (V528.49 release date: 02/08/2023). Now the latest weekly build doesn't auto-crash blender but I am still receiving this error:
![image](https://user-images.githubusercontent.com/65964807/221233517-324fd04f-1601-41c2-afd2-8bc12b1df7b4.png)

**Comment by bsavery** [comment]
Disable the viewport denoise and upscale.  Frankly we've been fighting the NV drivers quite a bit here, and have another solution coming in the future fr the long term.

**Comment by djtutorials** [comment]
Just an update- tried the new 3.5.5 and the issue is still present in the Final render setting. Interactive seems to work. Final renders black, throws and error then crashes.

**Comment by djtutorials** [comment]
Newest dev build 3.5 fixes the issues.
