### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by Hashlamoun** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#579]
## Issue
when i install plug in on blender apper this messege

3 Traceback (most recent call last):
File "/app/blender/3.4/scripts/modules/addon utils.py", line 333, in enable
mod = _ import_(module_name)
File " /home/mohammad/var/app/org.blender.Blender/config/blender/3.4/scripts/addons/rprblender/initpy",line52,in«module> from engine.viewport engine import Viewport Engine
File " /home/mohammad/var/app/org.blender.Blender/config/blender/3.4/scripts/addons/rprblender/engine/viewport_engine.py", line 32, in «module> from rprblender.utils import gl
File "/home/mohammad/var/app/org.blender.Blender/config/blender/3.4/scripts/addons/rprblender/utils/gi.py",line25,in<module>
gl = cdil.LoadLibrary(libGL.so')
File "/app/blender/3.4/pythor/lib/python3.10/ctypes/_ init_py", line 452, in LoadLibrary retum self. diltype(name)
File "/app/blender/3.4/pythor/lib/python3.10/ctypes/ init py", line 374, in init
self. handle = _dlopen(self name, mode)
OSEntor: libGL.so: cannot open shared object file: No such file or directory

## System Setup (Environment)
 Pop!_OS 22.04 LTS  //64-bit//
 3.4.1
 AMD® Ryzen 7 3700u with radeon vega mobile gfx × 8 // gpu AMD® Radeon vega 10 graphics

**Comment by G4br13lG0** [comment]
I think you may have to install amdgpu pro driver
Download link here : https://www.amd.com/en/support/linux-drivers
And and guide link here : https://www.amd.com/en/support/kb/faq/amdgpu-installation
