### ISSUE TITLE
[BUG] RPR not working on fedora 37

### ISSUE THREAD

**Issue by nequine** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#598]
Hello everyone !

I have been trying to make RPR work on my system but without much success, I always get this error when I try to enable RPR in the addon manager even though my graphic drivers are all up to date (mesa and nvidia):

```

Traceback (most recent call last):
  File "/opt/blender/blender-3.4.0-linux-x64/3.4/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/home/lorisc/.config/blender/3.4/scripts/addons/rprblender/__init__.py", line 52, in <module>
    from .engine.viewport_engine import ViewportEngine
  File "/home/lorisc/.config/blender/3.4/scripts/addons/rprblender/engine/viewport_engine.py", line 32, in <module>
    from rprblender.utils import gl
  File "/home/lorisc/.config/blender/3.4/scripts/addons/rprblender/utils/gl.py", line 25, in <module>
    gl = cdll.LoadLibrary('libGL.so')
  File "/opt/blender/blender-3.4.0-linux-x64/3.4/python/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/opt/blender/blender-3.4.0-linux-x64/3.4/python/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libGL.so: cannot open shared object file: No such file or directory
```

I am on a laptop with a nvidia 3080 mobile - Fedora 37, mesa-libGL-22.3.7-1.fc37 installed. 

Cheers !

**Comment by VladislavNekto** [comment]
You need symlink libGL.so.1 to libGL.so in /usr/lib64
