### ISSUE TITLE
rx 7900 xtx not working with ryzen 2700x 

### ISSUE THREAD

**Issue by xalteropsx** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#628]
![image](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/assets/103671642/25354dff-3f0d-4dcb-9a22-42c689d47892)

it happen when clicking cpu in right corner

![image](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/assets/103671642/c0c696e9-7444-4187-8429-31c83fd8dd9c)

**Comment by xalteropsx** [comment]
```
Read prefs: "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\config\userpref.blend"
2023-05-28 07:21:15,969 INFO rpr.engine.init [51164]:  Core version: 3.1.1 build 0x5c28d0d6
2023-05-28 07:21:15,980 INFO rpr.engine.init [51164]:  RIF version: 1.7.1 build 0xfdc139ba
Hardware raytracing support detected
2023-05-28 07:21:17,050 INFO rpr.material_library [51164]:  Material library located at C:\ProgramData\RadeonProRender\MaterialLibrary\Xml
Hardware raytracing support detected
WARN (bgl): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\generic\bgl.c:54 report_deprecated_call: 'bgl.glGenTextures' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.WARN (bgl): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\generic\bgl.c:54 report_deprecated_call: 'bgl.glBindTexture' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.WARN (bgl): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\generic\bgl.c:54 report_deprecated_call: 'bgl.glTexParameteri' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
WARN (bgl): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\generic\bgl.c:54 report_deprecated_call: 'bgl.glTexParameteri' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
WARN (bgl): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\generic\bgl.c:54 report_deprecated_call: 'bgl.glTexParameteri' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
WARN (bgl): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\generic\bgl.c:54 report_deprecated_call: 'bgl.glTexParameteri' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
WARN (bgl): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\generic\bgl.c:54 report_deprecated_call: 'bgl.glTexImage2D' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
WARN (bgl): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\generic\bgl.c:54 report_deprecated_call: 'bgl.glBindTexture' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.WARN (bgl): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\generic\bgl.c:54 report_deprecated_call: 'bgl.glEnable' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
WARN (bgl): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\generic\bgl.c:54 report_deprecated_call: 'bgl.glBlendFunc' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
2023-05-28 07:23:19,387 INFO rpr.utils.user_settings [51164]:  Automatic save user preferences...
Writing userprefs: "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\config\userpref.blend" ok
Info: Preferences saved
2023-05-28 07:23:30,968 ERROR rpr.init [51164]:  RPR call CreateContext(3145985, [1], 1, 17, <cdata 'void *[]' owning 24 bytes>, b'C:\\Users\\haide\\AppData\\Roaming\\Blender Foundation\\Blender\\3.6\\scripts\\addons\\rprblender\\.cache\\0x300101_hybridpro', <pyhybridpro.Context object at 0x00000270030DBAF0>) returned error code <-18> with error message: '' EXCEPTION: Traceback (most recent call last):
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\__init__.py", line 168, in view_update
    self.engine.sync(context, depsgraph)
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\engine\viewport_engine_hybridpro.py", line 51, in sync
    super().sync(context, depsgraph)
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\engine\viewport_engine.py", line 487, in sync
    scene.rpr.init_rpr_context(self.rpr_context, is_final_engine=False,
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\properties\render.py", line 706, in init_rpr_context
    rpr_context.init(context_flags, context_props)
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\engine\context_hybridpro.py", line 58, in init
    super().init(context_flags, context_props)
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\engine\context.py", line 98, in init
    self.context = self._Context(context_flags, context_props)
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\pyrpr.py", line 258, in __init__
    CreateContext(API_VERSION, [self.plugin_id], 1, flags,
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\pyrpr.py", line 74, in wrapped
    raise CoreError(status, f.__name__, argv, module_name)
pyrpr.CoreError: RPR call CreateContext(3145985, [1], 1, 17, <cdata 'void *[]' owning 24 bytes>, b'C:\\Users\\haide\\AppData\\Roaming\\Blender Foundation\\Blender\\3.6\\scripts\\addons\\rprblender\\.cache\\0x300101_hybridpro', <pyhybridpro.Context object at 0x00000270030DBAF0>) returned error code <-18> with error message: ''

2023-05-28 07:23:31,692 WARNING rpr.export.node [32436]:  Ignoring unsupported node <bpy_struct, ShaderNodeLightPath("Light Path") at 0x0000026FF2BB3A08, evaluated> <bpy_struct, Material("FloorHidden") atException ignored in: <function RPREngine.__del__ at 0x000002700281F910>
Traceback (most recent call last):
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\__init__.py", line 109, in __del__
    self.engine.stop_render()
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\engine\viewport_engine.py", line 225, in stop_render
    self.sync_render_thread.join()
AttributeError: 'NoneType' object has no attribute 'join'
2023-05-28 07:24:54,682 ERROR rpr.init [51164]:  RPR call CreateContext(3145985, [1], 1, 17, <cdata 'void *[]' owning 24 bytes>, b'C:\\Users\\haide\\AppData\\Roaming\\Blender Foundation\\Blender\\3.6\\scripts\\addons\\rprblender\\.cache\\0x300101_hybridpro', <pyhybridpro.Context object at 0x00000270030DB3A0>) returned error code <-18> with error message: '' EXCEPTION: Traceback (most recent call last):
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\__init__.py", line 168, in view_update
    self.engine.sync(context, depsgraph)
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\engine\viewport_engine_hybridpro.py", line 51, in sync
    super().sync(context, depsgraph)
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\engine\viewport_engine.py", line 487, in sync
    scene.rpr.init_rpr_context(self.rpr_context, is_final_engine=False,
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\properties\render.py", line 706, in init_rpr_context
    rpr_context.init(context_flags, context_props)
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\engine\context_hybridpro.py", line 58, in init
    super().init(context_flags, context_props)
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\engine\context.py", line 98, in init
    self.context = self._Context(context_flags, context_props)
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\pyrpr.py", line 258, in __init__
    CreateContext(API_VERSION, [self.plugin_id], 1, flags,
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\pyrpr.py", line 74, in wrapped
    raise CoreError(status, f.__name__, argv, module_name)
pyrpr.CoreError: RPR call CreateContext(3145985, [1], 1, 17, <cdata 'void *[]' owning 24 bytes>, b'C:\\Users\\haide\\AppData\\Roaming\\Blender Foundation\\Blender\\3.6\\scripts\\addons\\rprblender\\.cache\\0x300101_hybridpro', <pyhybridpro.Context object at 0x00000270030DB3A0>) returned error code <-18> with error message: ''

2023-05-28 07:26:38,593 INFO rpr.utils.user_settings [51164]:  Automatic save user preferences...
Writing userprefs: "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\config\userpref.blend" ok
Info: Preferences saved
Exception ignored in: <function RPREngine.__del__ at 0x000002700281F910>
Traceback (most recent call last):
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\__init__.py", line 109, in __del__
    self.engine.stop_render()
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\engine\viewport_engine.py", line 225, in stop_render
    self.sync_render_thread.join()
AttributeError: 'NoneType' object has no attribute 'join'
Hardware raytracing support detected

**Comment by ARozghon** [comment]
fixed in #629[https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/pull/629](url)
