### ISSUE TITLE
Radeon Pro Renderer is very unstable and barely works on my system.

### ISSUE THREAD

**Issue by SalsaAlex** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#638]
## Issue
When trying to render anything with the rx 550, blender just crashes without any error message crashes. in the log files it says "Fatal error: Unable to create Vulkan device, VkResult=-7"

Here's the debug log below:

```
I0705 13:43:57.810559  8160 device.cpp:47] CUEW initialization failed: Error opening the library
I0705 13:43:57.816557  8160 device.cpp:36] HIPEW initialization succeeded
I0705 13:43:57.818348  8160 device.cpp:38] Found precompiled kernels
2023-07-05 13:44:19,000 INFO rpr.engine.init [8160]:  Core version: 3.1.1 build 0x5c28d0d6
2023-07-05 13:44:19,013 INFO rpr.engine.init [8160]:  RIF version: 1.7.1 build 0xfdc139ba
2023-07-05 13:44:19,136 WARNING rpr.engine.init [8160]:  ('Plugin is not registered', WindowsPath('C:/Users/User/AppData/Roaming/Blender Foundation/Blender/3.6/scripts/addons/rprblender/HybridPro.dll'), -18, '')
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FFE1F3D0F1D
Module  : amdhip64.dll
Thread  : 000000d8
Switching to fully guarded memory allocator.
Blender 3.6.0
Build: 2023-06-27 08:27:30 Windows release
argv[0] = C:\Program Files (x86)\Steam\steamapps\common\Blender\\blender
argv[1] = --debug
argv[2] = --debug-cycles
argv[3] = --python-expr
argv[4] = import bpy; bpy.ops.wm.sysinfo(filepath=r'C:\Users\User\AppData\Local\Temp\blender\debug_logs\blender_system_info.txt')
Read prefs: "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.6\config\userpref.blend"
Warning: 16-bit calculations are not fully supported by device: Radeon RX550/550 Series
Error: Fatal error: Unable to create Vulkan device, VkResult=-7
ContextNode::Initialize: "Fatal error: Unable to create Vulkan device"
Writing: C:\Users\User\AppData\Local\Temp\blender.crash.txt
```

also, when trying to render the viewport, sometimes it manages to render the scene, but with an insane amount of RAM and VRAM usage while only rendering a basic cube with a solid color. and when it can't render the scene, a AMD bug report window pops up on my screen and this is what it says on blender's system console:

```
2023-07-05 14:18:21,285 INFO rpr.engine.init [3356]:  Core version: 3.1.1 build 0x5c28d0d6
2023-07-05 14:18:21,299 INFO rpr.engine.init [3356]:  RIF version: 1.7.1 build 0xfdc139ba
Warning: 16-bit calculations are not fully supported by device: Radeon RX550/550 Series
Error: Fatal error: Unable to create Vulkan device, VkResult=-7
ContextNode::Initialize: "Fatal error: Unable to create Vulkan device"
2023-07-05 14:18:21,454 WARNING rpr.engine.init [3356]:  ('Plugin is not registered', WindowsPath('C:/Users/Alex SSD/AppData/Roaming/Blender Foundation/Blender/3.6/scripts/addons/rprblender/HybridPro.dll'), -18, '')
Error: Failed to submit to a queue, VkResult=2
2023-07-05 14:18:44,572 ERROR rpr.viewport_engine [980]:  RPR call ContextRender(<pyhybrid.Context object at 0x000001974B6EC3D0>) returned error code <-18> with error message: '' EXCEPTION: Traceback (most recent call last):
  File "C:\Users\Alex SSD\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\engine\viewport_engine.py", line 463, in _do_sync_render
    self._do_render()
  File "C:\Users\Alex SSD\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\engine\viewport_engine.py", line 366, in _do_render
    self.rpr_context.render(restart=(iteration == 0))
  File "C:\Users\Alex SSD\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\engine\context.py", line 144, in render
    self.context.render()
  File "C:\Users\Alex SSD\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\pyhybrid.py", line 31, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\Alex SSD\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\pyhybrid.py", line 75, in render
    super().render()
  File "C:\Users\Alex SSD\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\pyrpr.py", line 286, in render
    ContextRender(self)
  File "C:\Users\Alex SSD\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\pyrpr.py", line 74, in wrapped
    raise CoreError(status, f.__name__, argv, module_name)
pyrpr.CoreError: RPR call ContextRender(<pyhybrid.Context object at 0x000001974B6EC3D0>) returned error code <-18> with error message: ''

Error: Failed to submit to a queue, VkResult=-4
2023-07-05 14:18:45,298 ERROR rpr.init [3356]:  RPR call FrameBufferGetInfo(<pyrpr.FrameBuffer object at 0x000001974B6EC5E0>, 4867, 10503936, <cdata 'float *' 0x00000198883D3400>, <cdata 'void *' NULL>) returned error code <-18> with error message: '' EXCEPTION: Traceback (most recent call last):
  File "C:\Users\Alex SSD\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\__init__.py", line 178, in view_draw
    self.engine.draw(context)
  File "C:\Users\Alex SSD\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\engine\viewport_engine.py", line 869, in draw
    self._draw(context.scene)
  File "C:\Users\Alex SSD\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\engine\viewport_engine.py", line 836, in _draw
    self._resolve()
  File "C:\Users\Alex SSD\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\engine\viewport_engine_hybrid.py", line 45, in _resolve
    self.render_image = self.rpr_context.get_image()
  File "C:\Users\Alex SSD\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\engine\context.py", line 152, in get_image
    return self.get_frame_buffer(aov_type).get_data()
  File "C:\Users\Alex SSD\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\pyrpr.py", line 954, in get_data
    FrameBufferGetInfo(self, FRAMEBUFFER_DATA, self.size(), ffi.cast('float*', data.ctypes.data), ffi.NULL)
  File "C:\Users\Alex SSD\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\rprblender\pyrpr.py", line 74, in wrapped
    raise CoreError(status, f.__name__, argv, module_name)
pyrpr.CoreError: RPR call FrameBufferGetInfo(<pyrpr.FrameBuffer object at 0x000001974B6EC5E0>, 4867, 10503936, <cdata 'float *' 0x00000198883D3400>, <cdata 'void *' NULL>) returned error code <-18> with error message: ''
```

## Steps to Reproduce
1. Launch blender and render the basic cube scene with a rx 550
2. Blender crashes

## System Setup (Environment)
Windows 10 22h2 64 bit
RX 550 4GB VRAM - AMD Software Adrenalin Version 23.5.2
Intel I7-2600
8 GB RAM
Blender 3.6.0
Rendered using only GPU

**Comment by ARozghon** [comment]
you have an answer in this log:
_Warning: 16-bit calculations are not fully supported by device: Radeon RX550/550 Series_
so, this provides the result:
_Error: Fatal error: Unable to create Vulkan device, VkResult=-7_
also, RPR now switch to the HIP and HIP not support old GPUs

**Comment by bsavery** [comment]
You can try setting the "Viewport mode" to "RPR - Final", then in the debug / advanced settings set it to use OpenCL.

**Comment by SalsaAlex** [comment]
> You can try setting the "Viewport mode" to "RPR - Final", then in the debug / advanced settings set it to use OpenCL.

that seemed to fix it, thanks!
