### ISSUE TITLE
Blender 3.6 - Can't enable RPR (v3.6.0)

### ISSUE THREAD

**Issue by mobilex1122** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#642]
Blender shows error when enabling RPR (v3.6.0)

## Issue

Blender showed Popup error instead of enabling AMD RPR.
I tried multiple versions on AMD RPR but no one works.

## Steps to Reproduce
1. Open Settings
2. Go to Addons
3. Enable RPR Addon
4. Blender will show Error Popup (Image in Details)

## System Setup (Environment)

**OS:** EndeavourOS  (v2023.3.6) - Gnome Edition

**CPU:** Intel i5 (11gen)
**GPU:** AMD Radeon RX 6600

**Blender Version:** 3.6.

**Render Device:** GPU

## Detailed Description

Error Popup:
![image](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/assets/60009551/e6559ffd-7c3e-4d9d-8cde-4c04413efab5)

Error Log:
```
Traceback (most recent call last):
  File "/usr/share/blender/3.6/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mobilex/.config/blender/3.6/scripts/addons/rprblender/__init__.py", line 40, in <module>
    from .engine.engine import Engine
  File "/home/mobilex/.config/blender/3.6/scripts/addons/rprblender/engine/__init__.py", line 55, in <module>
    pyrpr.init(rpr_lib_dir, logging.Log(tag='core'), config.pyrpr_log_calls)
  File "/home/mobilex/.config/blender/3.6/scripts/addons/rprblender/pyrpr.py", line 110, in init
    import __rpr
  File "/home/mobilex/.config/blender/3.6/scripts/addons/rprblender/__rpr.py", line 2, in <module>
    import _cffi_backend
ModuleNotFoundError: No module named '_cffi_backend'
```

**Comment by mobilex1122** [comment]
I sloved the issue here is the solution for those who has the same problem:
On arch distributions you need to install `python-pip` pacman package (It installs all requied modules for RPR to work).
