### ISSUE TITLE
interactive Render failed to start rendering

### ISSUE THREAD

**Issue by roman-source** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#646]
1.  System setup (GTX 1650, Ryzen 5 2600, OS version - win 10, Blender version: 3.6.1

Error message:

Warning: No supported ray tracing API. Building acceleration structures will be unavailable
Hardware raytracing support has not been detected, falling back to software raytracing
2023-08-09 02:02:43,471 ERROR rpr.viewport_engine [2568]:  RPR call ContextCreateCurve(<pyhybridpro.Context object at 0x0000021966B36E90>, <pyhybridpro.Curve object at 0x0000021966B378E0>, 957140, <cdata 'float *' 0x00000219D1F307C0>, 12, 957140, 47857, <cdata 'unsigned int *' 0x00000219BD9C0800>, <cdata 'float *' 0x00000219BB210B80>, <cdata 'float *' 0x00000219BAEB0340>, <cdata 'int *' 0x0000021978526C40>, 1) returned error code <-12> with error message: '' EXCEPTION: Traceback (most recent call last):
  File "C:\Blender\Blender 3.6\3.6\scripts\addons\rprblender\engine\viewport_engine.py", line 462, in _do_sync_render
    self._do_sync(depsgraph)
  File "C:\Blender\Blender 3.6\3.6\scripts\addons\rprblender\engine\viewport_engine.py", line 260, in _do_sync
    object.sync(self.rpr_context, obj,
  File "C:\Blender\Blender 3.6\3.6\scripts\addons\rprblender\export\object.py", line 60, in sync
    hair.sync_curves(rpr_context, obj)
  File "C:\Blender\Blender 3.6\3.6\scripts\addons\rprblender\export\hair.py", line 255, in sync_curves
    rpr_hair = rpr_context.create_curve_object(obj_key, curve_data.points, curve_data.points_radii, curve_data.uvs)
  File "C:\Blender\Blender 3.6\3.6\scripts\addons\rprblender\engine\context.py", line 472, in create_curve_object
    curve = self._Curve(self.context, control_points, points_radii, uvs)
  File "C:\Blender\Blender 3.6\3.6\scripts\addons\rprblender\pyrpr.py", line 647, in __init__
    ContextCreateCurve(self.context, self,
  File "C:\Blender\Blender 3.6\3.6\scripts\addons\rprblender\pyrpr.py", line 74, in wrapped
    raise CoreError(status, f.__name__, argv, module_name)
pyrpr.CoreError: RPR call ContextCreateCurve(<pyhybridpro.Context object at 0x0000021966B36E90>, <pyhybridpro.Curve object at 0x0000021966B378E0>, 957140, <cdata 'float *' 0x00000219D1F307C0>, 12, 957140, 47857, <cdata 'unsigned int *' 0x00000219BD9C0800>, <cdata 'float *' 0x00000219BB210B80>, <cdata 'float *' 0x00000219BAEB0340>, <cdata 'int *' 0x0000021978526C40>, 1) returned error code <-12> with error message: ''

## Issue

![image](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/assets/77725171/4bd001e0-a2c1-409f-a943-c5bfa90ab045)
interactive Render failed to start rendering
## System Setup (Environment)
Win 10
GTX 1650, Ryzen 5 2600 (gpu driver version: 531.79)
Blender version: 3.6.1
Using GPU render

## Detailed Description
1. open this blend file:  https://www.blender.org/download/demo/geometry-nodes/hair_nodes-female_hair_styles.blend
2. switch Viewport Shading to Rendered

**Comment by roman-source** [comment]
Addon version 3.6.0
I really hope that in future versions of the addon will be more stable, I really want to move completely to the Radeon prorender, no rendering engine did not give such a speed of rendering, as this engine in interactive mode. I tested it on different scenes and it's amazing!!!! BUT unfortunately in some scenes it gives errors (quite often) and also often crashes completely with blender.

Translated with www.DeepL.com/Translator (free version)
