### ISSUE TITLE
hi? When will it be updated to Blender 4.0?

### ISSUE THREAD

**Issue by difaandailisi** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#668]
The plug-in cannot be imported, and a traceback window pops up

**Comment by feniksa** [comment]
Hi @difaandailisi @mobilex1122 

Work for blender 4.0 under process. AMD should release as soon as possible.

**Comment by jakubbys** [comment]
The 3.6.10 development build also fixes RX 6400 support.

**Comment by feniksa** [comment]
Hi guys,

Please, use build: https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.6.10 

This is release candidate.

**Comment by BrunoDSL** [comment]
While the add-on gets imported, it generates this traceback when trying to enable it. Tested with a Radeon RX550 running with the 22.Q4 Pro Drivers. I also tested with the Adrenalin 22.14 drivers and the same error shows up:

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Bruno de Souza Lino\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\__init__.py", line 40, in <module>
    from .engine.engine import Engine
  File "C:\Users\Bruno de Souza Lino\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\engine\__init__.py", line 119, in <module>
    pyrpr2.Context.load_devices()
  File "C:\Users\Bruno de Souza Lino\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\pyrpr2.py", line 29, in load_devices
    super().load_devices()
  File "C:\Users\Bruno de Souza Lino\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\pyrpr.py", line 231, in load_devices
    device = get_device(create_flag, getattr(pyrprwrap, 'CONTEXT_GPU%d_NAME' % i))
  File "C:\Users\Bruno de Souza Lino\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\pyrpr.py", line 223, in get_device
    raise err
  File "C:\Users\Bruno de Souza Lino\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\pyrpr.py", line 212, in get_device
    context = cls(create_flag)
  File "C:\Users\Bruno de Souza Lino\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\pyrpr2.py", line 23, in __init__
    super().__init__(flags, props, use_cache)
  File "C:\Users\Bruno de Souza Lino\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\pyrpr.py", line 256, in __init__
    CreateContext(API_VERSION, [self.plugin_id], 1, flags,
  File "C:\Users\Bruno de Souza Lino\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\pyrpr.py", line 72, in wrapped
    raise CoreError(status, f.__name__, argv, module_name)
pyrpr.CoreError: RPR call CreateContext(3145988, [0], 1, 1, <cdata 'void *' NULL>, b'C:\\Users\\Bruno de Souza Lino\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\rprblender\\.cache\\0x300104_rpr2', <pyrpr2.Context object at 0x000001F94D174E50>) returned error code <-4> with error message: ''
```

**Comment by feniksa** [comment]
@BrunoDSL ContextCreate returned error "ShaderCompilationError". 

Unfortunately,  AMD RX550 architecture is not supported by HIP -> ProRender SDK -> blender addon. 

It is possible to force old OpenCL hw acceleration mechanism in Blender addon in settings:

Settings: Debug -> Use OpenCL. 
![image](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/assets/379911/c872ca9c-873a-4f11-859e-8327d6b9d211)

Please, be aware that OpenCL backend is NOT recommend and only and only for debug purposes.

**Comment by BrunoDSL** [comment]
> @BrunoDSL ContextCreate returned error "ShaderCompilationError".
> 
> Unfortunately, AMD RX550 architecture is not supported by HIP -> ProRender SDK -> blender addon.
> 
> It is possible to force old OpenCL hw acceleration mechanism in Blender addon in settings:
> 
> Settings: Debug -> Use OpenCL. ![image](https://private-user-images.githubusercontent.com/379911/316314677-c872ca9c-873a-4f11-859e-8327d6b9d211.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMDA4MDUsIm5iZiI6MTcxMTMwMDUwNSwicGF0aCI6Ii8zNzk5MTEvMzE2MzE0Njc3LWM4NzJjYTljLTg3M2EtNGYxMS04NTllLTgzMjdkNmI5ZDIxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxNzE1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGRjNzdiMTQzZDQ0YjZjZWNkOTk5ODk4OGIyZWMzYmYzYTA0MTYyMTE0MWQ1MjJlMzYyMjFiZTVjYTIyNjM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FGsV4Ag7OxzPr2bFHWL_JFVbYtAqOQbZqsD-TmDqcHk)
> 
> Please, be aware that OpenCL backend is NOT recommend and only and only for debug purposes.

That's not possible to do because you don't have access to those options if the plugin is not enabled. This traceback appears when enabling the plugin

**Comment by feniksa** [comment]
> This is a bit confusing, since ProRender is supposedly compatible with every RX card as per their system requirements.
It looks like documentation may be slightly outdated and give misunderstand. For today, GCN architecture in "support mode" (https://www.anandtech.com/show/21126/amd-reduces-ongoing-driver-support-for-polaris-and-vega-gpus). 

It mins only critical bug-fixes or security fixes for GCN based GPU's .

**Comment by BrunoDSL** [comment]
It seems to still work with Blender 3.6 LTS using version 3.5 of the plugin. Version 3.6 started using HIP instead of OpenCL apparently, though only for `RPR Final`
