### ISSUE TITLE
v3.6.10 Material Library fails to add Output node in Blender 4.0.2

### ISSUE THREAD

**Issue by knightknight** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#673]
Every issue should include 3 things:
1.  System setup (GPU, CPU, OS version, Blender version)

- Radeon RX 5500 XT
- AMD Ryzen 7 2700 Eight-Core Processor, 3200 Mhz, 8 Core(s), 16 Logical Processor(s)
- Microsoft Windows 11 Pro
- Version	10.0.22621 Build 22621
- Blender 4.0.2
- RadeonProRenderForBlender_3.6.10_Windows.release

4.  What the expected behavior or effect is.  If possible include the error message. 

Material library fails to load the correct nodes, instead showing the default Blender purple missing material on the object.

```bash
2024-03-25 20:50:28,809 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: refraction.color, value: 1, 1, 1, 1)
2024-03-25 20:50:28,810 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: refraction.weight, value: 0, 0, 0, 0)
2024-03-25 20:50:28,810 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: refraction.roughness, value: 0, 0, 0, 0)
2024-03-25 20:50:28,810 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: refraction.ior, value: 1.5, 1.5, 1.5, 1.5)
2024-03-25 20:50:28,810 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: refraction.absorptionColor, value: 1, 1, 1, 0)
2024-03-25 20:50:28,811 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: refraction.absorptionDistance, value: 1, 1, 1, 0)
2024-03-25 20:50:28,811 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: coating.color, value: 1, 1, 1, 0)
2024-03-25 20:50:28,811 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: coating.weight, value: 1, 1, 1, 1)
2024-03-25 20:50:28,811 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: coating.roughness, value: 0, 0, 0, 0)
2024-03-25 20:50:28,811 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: coating.ior, value: 2.3, 2.3, 2.3, 2.3)
2024-03-25 20:50:28,812 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: coating.transmissionColor, value: 0, 0, 0, 1)
2024-03-25 20:50:28,812 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: coating.thickness, value: 0, 0, 0, 0)
2024-03-25 20:50:28,812 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: sheen, value: 1, 1, 1, 1)
2024-03-25 20:50:28,813 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: sheen.tint, value: 0, 0, 0, 0)
2024-03-25 20:50:28,813 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: sheen.weight, value: 0, 0, 0, 0)
2024-03-25 20:50:28,813 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: emission.color, value: 1, 1, 1, 1)
2024-03-25 20:50:28,813 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: emission.weight, value: 0, 0, 0, 0)
2024-03-25 20:50:28,814 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: transparency, value: 0, 0, 0, 0)
2024-03-25 20:50:28,814 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: sss.scatterColor, value: 0, 0, 0, 0)
2024-03-25 20:50:28,814 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: sss.scatterDistance, value: 0, 0, 0, 0)
2024-03-25 20:50:28,815 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: sss.scatterDirection, value: 0, 0, 0, 0)
2024-03-25 20:50:28,815 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: sss.weight, value: 0, 0, 0, 0)
2024-03-25 20:50:28,816 WARNING rpr.material_loader [17716]:  compile_input_special fails (socket_name: backscatter.color, value: 1, 1, 1, 1)
Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\operators\material_library.py", line 45, in execute
    material_library.import_xml_material(context.material, material_name, xml_path, properties.copy_textures)
  File "C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\material_library\__init__.py", line 81, in import_xml_material
    closure = compile_material_from_xml(xml_path, material.node_tree, image_loader)
  File "C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\material_library\__init__.py", line 126, in compile_material_from_xml
    return RPRXMLMaterialCompiler(nodes, node_tree, image_loader).compile(root_node)
  File "C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\material_library\loader.py", line 40, in compile
    closure = self.compile_node(node)
  File "C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\material_library\loader.py", line 91, in compile_node
    node_compiler.update_node()
  File "C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\material_library\loader.py", line 408, in update_node
    backscatter_color = self.get_input_socket('backscatter.color').default_value
AttributeError: 'NoneType' object has no attribute 'default_value'
Error: Python: Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\operators\material_library.py", line 45, in execute
    material_library.import_xml_material(context.material, material_name, xml_path, properties.copy_textures)
  File "C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\material_library\__init__.py", line 81, in import_xml_material
    closure = compile_material_from_xml(xml_path, material.node_tree, image_loader)
  File "C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\material_library\__init__.py", line 126, in compile_material_from_xml
    return RPRXMLMaterialCompiler(nodes, node_tree, image_loader).compile(root_node)
  File "C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\material_library\loader.py", line 40, in compile
    closure = self.compile_node(node)
  File "C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\material_library\loader.py", line 91, in compile_node
    node_compiler.update_node()
  File "C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\material_library\loader.py", line 408, in update_node
    backscatter_color = self.get_input_socket('backscatter.color').default_value
AttributeError: 'NoneType' object has no attribute 'default_value'

2024-03-25 20:50:28,825 ERROR rpr.export.rpr_nodes [17716]:  ('Incorrect Surface input socket', None, <bpy_struct, ShaderNodeOutputMaterial("Material Output") at 0x0000019A1F077888, evaluated>, <bpy_struct, Material("EastwoodRoyalBlue Metallic.001") at 0x0000019A1E43EE08, evaluated>)
2024-03-25 20:50:28,852 ERROR rpr.export.rpr_nodes [20068]:  ('Incorrect Surface input socket', None, <bpy_struct, ShaderNodeOutputMaterial("Material Output") at 0x000001992E5B6E08, evaluated>, <bpy_struct, Material("EastwoodRoyalBlue Metallic.001") at 0x0000019930C34588, evaluated>)
2024-03-25 20:50:28,855 WARNING rpr.export.node [20068]:  Ignoring unsupported node <bpy_struct, ShaderNodeLightPath("Light Path") at 0x0000019A30C45F08, evaluated> <bpy_struct, Material("FloorHidden") at 0x0000019A30970D08, evaluated>
```

## Issue

Default Blender purple missing material

![Missing-Output-Node](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/assets/5765628/c70e2c7b-d48e-4220-bb75-28524ca031be)

## Steps to Reproduce

- Switch Render Engine to ProRender
- Add Cube to scene
- Select cube open the Materials tab and under Material Library select any material 'Import Material'
- Material is added but missing the Output node instead defaults to Blenders missing material colour

## System Setup (Environment)

- Blender Launcher v2.0.24

```bash
====================================
= Blender 4.0.2 System Information =
====================================


Blender:
====================================

version: 4.0.2, branch: blender-v4.0-release, commit date: 2023-12-05 07:41, hash: 9be62e85b727, type: release
build date: 2023-12-05, 13:01:12
platform: 'Windows-10-10.0.22621-SP0'
binary path: 'C:\\Blender\\stable\\blender-4.0\\blender.exe'
build cflags: /W3 /w34062 /w34100 /w34115 /w34189 /w35038 /wd4018 /wd4146 /wd4065 /wd4127 /wd4181 /wd4200 /wd4244 /wd4267 /wd4305 /wd4800 /wd4828 /wd4996 /wd4661 /wd4848 /we4013 /we4133 /we4431 /we4033 /DWIN32 /D_WINDOWS /W3 /nologo /J /Gd /MP /bigobj /Zc:inline -openmp   
build cxxflags: /W3 /w34062 /w34100 /w34115 /w34189 /w35038 /wd4018 /wd4146 /wd4065 /wd4127 /wd4181 /wd4200 /wd4244 /wd4267 /wd4305 /wd4800 /wd4828 /wd4996 /wd4661 /wd4848 /we4013 /we4133 /we4431 /we4033 /DWIN32 /D_WINDOWS /W3  /EHsc /nologo /J /Gd /MP /EHsc /bigobj /Zc:inline /permissive- -openmp /Zc:__cplusplus   
build linkflags: /MACHINE:X64  /SUBSYSTEM:CONSOLE /STACK:2097152 /ignore:4049 /ignore:4217 /ignore:4221
build system: CMake

Python:
====================================

version: 3.10.13 (main, Sep 20 2023, 07:33:17) [MSC v.1928 64 bit (AMD64)]
file system encoding: utf-8:surrogatepass
paths:
	'C:\\Users\\<username>\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\startup'
	'C:\\Blender\\stable\\blender-4.0\\4.0\\scripts\\startup'
	'C:\\Blender\\stable\\blender-4.0\\4.0\\scripts\\modules'
	'C:\\Blender\\stable\\blender-4.0\\python310.zip'
	'C:\\Blender\\stable\\blender-4.0\\4.0\\python\\DLLs'
	'C:\\Blender\\stable\\blender-4.0\\4.0\\python\\lib'
	'C:\\Blender\\stable\\blender-4.0\\4.0\\python\\bin'
	'C:\\Users\\<username>\\AppData\\Roaming\\Python\\Python310\\site-packages'
	'C:\\Blender\\stable\\blender-4.0\\4.0\\python'
	'C:\\Blender\\stable\\blender-4.0\\4.0\\python\\lib\\site-packages'
	'C:\\Blender\\stable\\blender-4.0\\4.0\\scripts\\freestyle\\modules'
	'C:\\Blender\\stable\\blender-4.0\\4.0\\scripts\\addons\\modules'
	'C:\\Users\\<username>\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\modules'
	'C:\\Blender\\stable\\blender-4.0\\4.0\\scripts\\addons'
	'C:\\Users\\<username>\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons'
	'C:\\Blender\\stable\\blender-4.0\\4.0\\scripts\\addons_contrib'
	'C:\\Users\\<username>\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\rprblender'

Python (External Binary):
====================================

binary path: 'C:\\Blender\\stable\\blender-4.0\\4.0\\python\\bin\\python.exe'
version: Python 3.10.13

Directories:
====================================

scripts:
	'C:\\Blender\\stable\\blender-4.0\\4.0\\scripts'
	'C:\\Users\\<username>\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts'
user scripts: 'C:\\Users\\<username>\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts'
pref scripts:
datafiles: 'C:\\Users\\<username>\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\datafiles'
config: 'C:\\Users\\<username>\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\config'
scripts: 'C:\\Users\\<username>\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts'
autosave: 'C:\\Users\\<username>\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\autosave'
tempdir: 'C:\\Users\\<username>\\AppData\\Local\\Temp\\blender_a17716\\'

FFmpeg:
====================================

avcodec:   '60,  3, 100'
avdevice:  '60,  1, 100'
avformat:  '60,  3, 100'
avutil:    '58,  2, 100'
swscale:   ' 7,  1, 100'

SDL:
====================================

Version: 2.28.2
Loading method: linked (WITH_SDL_DYNLOAD=OFF)

Other Libraries:
====================================

OpenColorIO:  2,  2,  0
OpenImageIO:  2,  4, 15
OpenShadingLanguage:  1, 13,  0
OpenSubdiv:  3,  5,  0
OpenVDB: 10,  0,  0
Alembic:  1,  8,  3
USD:  0, 23,  5

GPU:
====================================

renderer:	'Radeon RX 5500 XT'
vendor:		'ATI Technologies Inc.'
version:	'4.6.0 Core Profile Context 24.3.1.240312'
device type:	'AMD'
backend type:	'OPENGL'
extensions:
	GL_AMD_blend_minmax_factor
	GL_AMD_conservative_depth
	GL_AMD_debug_output
	GL_AMD_depth_clamp_separate
	GL_AMD_gpu_shader_half_float
	GL_AMD_gpu_shader_int16
	GL_AMD_gpu_shader_int64
	GL_AMD_multi_draw_indirect
	GL_AMD_pinned_memory
	GL_AMD_query_buffer_object
	GL_AMD_sample_positions
	GL_AMD_seamless_cubemap_per_texture
	GL_AMD_shader_trinary_minmax
	GL_AMD_texture_cube_map_array
	GL_AMD_vertex_shader_layer
	GL_AMD_vertex_shader_viewport_index
	GL_ARB_ES2_compatibility
	GL_ARB_ES3_1_compatibility
	GL_ARB_ES3_2_compatibility
	GL_ARB_ES3_compatibility
	GL_ARB_arrays_of_arrays
	GL_ARB_base_instance
	GL_ARB_bindless_texture
	GL_ARB_blend_func_extended
	GL_ARB_buffer_storage
	GL_ARB_clear_buffer_object
	GL_ARB_clear_texture
	GL_ARB_clip_control
	GL_ARB_color_buffer_float
	GL_ARB_compressed_texture_pixel_storage
	GL_ARB_compute_shader
	GL_ARB_conditional_render_inverted
	GL_ARB_conservative_depth
	GL_ARB_copy_buffer
	GL_ARB_copy_image
	GL_ARB_cull_distance
	GL_ARB_debug_output
	GL_ARB_depth_buffer_float
	GL_ARB_depth_clamp
	GL_ARB_depth_texture
	GL_ARB_derivative_control
	GL_ARB_direct_state_access
	GL_ARB_draw_buffers
	GL_ARB_draw_buffers_blend
	GL_ARB_draw_elements_base_vertex
	GL_ARB_draw_indirect
	GL_ARB_draw_instanced
	GL_ARB_enhanced_layouts
	GL_ARB_explicit_attrib_location
	GL_ARB_explicit_uniform_location
	GL_ARB_fragment_coord_conventions
	GL_ARB_fragment_layer_viewport
	GL_ARB_fragment_program
	GL_ARB_fragment_program_shadow
	GL_ARB_fragment_shader
	GL_ARB_framebuffer_no_attachments
	GL_ARB_framebuffer_object
	GL_ARB_framebuffer_sRGB
	GL_ARB_geometry_shader4
	GL_ARB_get_program_binary
	GL_ARB_get_texture_sub_image
	GL_ARB_gl_spirv
	GL_ARB_gpu_shader5
	GL_ARB_gpu_shader_fp64
	GL_ARB_gpu_shader_int64
	GL_ARB_half_float_pixel
	GL_ARB_half_float_vertex
	GL_ARB_indirect_parameters
	GL_ARB_instanced_arrays
	GL_ARB_internalformat_query
	GL_ARB_internalformat_query2
	GL_ARB_invalidate_subdata
	GL_ARB_map_buffer_range
	GL_ARB_multi_bind
	GL_ARB_multi_draw_indirect
	GL_ARB_multisample
	GL_ARB_multitexture
	GL_ARB_occlusion_query
	GL_ARB_occlusion_query2
	GL_ARB_parallel_shader_compile
	GL_ARB_pipeline_statistics_query
	GL_ARB_pixel_buffer_object
	GL_ARB_point_parameters
	GL_ARB_point_sprite
	GL_ARB_polygon_offset_clamp
	GL_ARB_post_depth_coverage
	GL_ARB_program_interface_query
	GL_ARB_provoking_vertex
	GL_ARB_query_buffer_object
	GL_ARB_robustness
	GL_ARB_sample_locations
	GL_ARB_sample_shading
	GL_ARB_sampler_objects
	GL_ARB_seamless_cube_map
	GL_ARB_seamless_cubemap_per_texture
	GL_ARB_separate_shader_objects
	GL_ARB_shader_atomic_counter_ops
	GL_ARB_shader_atomic_counters
	GL_ARB_shader_ballot
	GL_ARB_shader_bit_encoding
	GL_ARB_shader_clock
	GL_ARB_shader_draw_parameters
	GL_ARB_shader_group_vote
	GL_ARB_shader_image_load_store
	GL_ARB_shader_image_size
	GL_ARB_shader_objects
	GL_ARB_shader_precision
	GL_ARB_shader_stencil_export
	GL_ARB_shader_storage_buffer_object
	GL_ARB_shader_subroutine
	GL_ARB_shader_texture_image_samples
	GL_ARB_shader_texture_lod
	GL_ARB_shader_viewport_layer_array
	GL_ARB_shading_language_100
	GL_ARB_shading_language_420pack
	GL_ARB_shading_language_packing
	GL_ARB_shadow
	GL_ARB_shadow_ambient
	GL_ARB_sparse_buffer
	GL_ARB_sparse_texture
	GL_ARB_spirv_extensions
	GL_ARB_stencil_texturing
	GL_ARB_sync
	GL_ARB_tessellation_shader
	GL_ARB_texture_barrier
	GL_ARB_texture_border_clamp
	GL_ARB_texture_buffer_object
	GL_ARB_texture_buffer_object_rgb32
	GL_ARB_texture_buffer_range
	GL_ARB_texture_compression
	GL_ARB_texture_compression_bptc
	GL_ARB_texture_compression_rgtc
	GL_ARB_texture_cube_map
	GL_ARB_texture_cube_map_array
	GL_ARB_texture_env_add
	GL_ARB_texture_env_combine
	GL_ARB_texture_env_crossbar
	GL_ARB_texture_env_dot3
	GL_ARB_texture_filter_anisotropic
	GL_ARB_texture_filter_minmax
	GL_ARB_texture_float
	GL_ARB_texture_gather
	GL_ARB_texture_mirror_clamp_to_edge
	GL_ARB_texture_mirrored_repeat
	GL_ARB_texture_multisample
	GL_ARB_texture_multisample_no_array
	GL_ARB_texture_non_power_of_two
	GL_ARB_texture_query_levels
	GL_ARB_texture_query_lod
	GL_ARB_texture_rectangle
	GL_ARB_texture_rg
	GL_ARB_texture_rgb10_a2ui
	GL_ARB_texture_stencil8
	GL_ARB_texture_storage
	GL_ARB_texture_storage_multisample
	GL_ARB_texture_swizzle
	GL_ARB_texture_view
	GL_ARB_timer_query
	GL_ARB_transform_feedback
	GL_ARB_transform_feedback2
	GL_ARB_transform_feedback3
	GL_ARB_transform_feedback_instanced
	GL_ARB_transform_feedback_overflow_query
	GL_ARB_transpose_matrix
	GL_ARB_uniform_buffer_object
	GL_ARB_vertex_array_bgra
	GL_ARB_vertex_array_object
	GL_ARB_vertex_attrib_64bit
	GL_ARB_vertex_attrib_binding
	GL_ARB_vertex_buffer_object
	GL_ARB_vertex_program
	GL_ARB_vertex_shader
	GL_ARB_vertex_type_10f_11f_11f_rev
	GL_ARB_vertex_type_2_10_10_10_rev
	GL_ARB_viewport_array
	GL_ARB_window_pos
	GL_ATI_draw_buffers
	GL_ATI_meminfo
	GL_ATI_separate_stencil
	GL_ATI_shader_texture_lod
	GL_ATI_texture_env_combine3
	GL_ATI_texture_float
	GL_ATI_texture_mirror_once
	GL_EXT_abgr
	GL_EXT_bgra
	GL_EXT_bindable_uniform
	GL_EXT_blend_color
	GL_EXT_blend_equation_separate
	GL_EXT_blend_func_separate
	GL_EXT_blend_minmax
	GL_EXT_blend_subtract
	GL_EXT_compiled_vertex_array
	GL_EXT_copy_buffer
	GL_EXT_copy_texture
	GL_EXT_debug_label
	GL_EXT_depth_bounds_test
	GL_EXT_direct_state_access
	GL_EXT_draw_buffers2
	GL_EXT_draw_instanced
	GL_EXT_draw_range_elements
	GL_EXT_fog_coord
	GL_EXT_framebuffer_blit
	GL_EXT_framebuffer_multisample
	GL_EXT_framebuffer_object
	GL_EXT_framebuffer_sRGB
	GL_EXT_geometry_shader4
	GL_EXT_gpu_program_parameters
	GL_EXT_gpu_shader4
	GL_EXT_memory_object
	GL_EXT_memory_object_win32
	GL_EXT_multi_draw_arrays
	GL_EXT_nonuniform_qualifier
	GL_EXT_packed_depth_stencil
	GL_EXT_packed_float
	GL_EXT_packed_pixels
	GL_EXT_pixel_buffer_object
	GL_EXT_point_parameters
	GL_EXT_polygon_offset_clamp
	GL_EXT_provoking_vertex
	GL_EXT_rescale_normal
	GL_EXT_secondary_color
	GL_EXT_semaphore
	GL_EXT_semaphore_win32
	GL_EXT_separate_specular_color
	GL_EXT_shader_image_load_store
	GL_EXT_shader_integer_mix
	GL_EXT_shadow_funcs
	GL_EXT_stencil_wrap
	GL_EXT_subtexture
	GL_EXT_texture
	GL_EXT_texture3D
	GL_EXT_texture_array
	GL_EXT_texture_buffer_object
	GL_EXT_texture_compression_bptc
	GL_EXT_texture_compression_latc
	GL_EXT_texture_compression_rgtc
	GL_EXT_texture_compression_s3tc
	GL_EXT_texture_cube_map
	GL_EXT_texture_edge_clamp
	GL_EXT_texture_env_add
	GL_EXT_texture_env_combine
	GL_EXT_texture_env_dot3
	GL_EXT_texture_filter_anisotropic
	GL_EXT_texture_integer
	GL_EXT_texture_lod
	GL_EXT_texture_lod_bias
	GL_EXT_texture_mirror_clamp
	GL_EXT_texture_object
	GL_EXT_texture_rectangle
	GL_EXT_texture_sRGB
	GL_EXT_texture_sRGB_R8
	GL_EXT_texture_sRGB_RG8
	GL_EXT_texture_sRGB_decode
	GL_EXT_texture_shared_exponent
	GL_EXT_texture_snorm
	GL_EXT_texture_storage
	GL_EXT_texture_swizzle
	GL_EXT_timer_query
	GL_EXT_transform_feedback
	GL_EXT_vertex_array
	GL_EXT_vertex_array_bgra
	GL_EXT_vertex_attrib_64bit
	GL_IBM_texture_mirrored_repeat
	GL_KHR_blend_equation_advanced
	GL_KHR_blend_equation_advanced_coherent
	GL_KHR_debug
	GL_KHR_no_error
	GL_KHR_parallel_shader_compile
	GL_KHR_robust_buffer_access_behavior
	GL_KHR_robustness
	GL_KHR_shader_subgroup
	GL_KHR_texture_compression_astc_ldr
	GL_NV_blend_square
	GL_NV_conditional_render
	GL_NV_copy_image
	GL_NV_depth_buffer_float
	GL_NV_float_buffer
	GL_NV_half_float
	GL_NV_primitive_restart
	GL_NV_shader_atomic_int64
	GL_NV_texgen_reflection
	GL_NV_texture_barrier
	GL_NV_timeline_semaphore
	GL_OES_EGL_image
	GL_OVR_multiview
	GL_OVR_multiview2
	GL_S3_s3tc
	GL_SGIS_generate_mipmap
	GL_SGIS_texture_edge_clamp
	GL_SGIS_texture_lod
	GL_SUN_multi_draw_arrays
	WGL_EXT_swap_control

Implementation Dependent GPU Limits:
====================================

Maximum Batch Vertices:	536870911
Maximum Batch Indices:	536870911

GLSL:
Maximum Varying Floats:	64
Maximum Vertex Attributes:	32
Maximum Vertex Uniform Components:	8000
Maximum Fragment Uniform Components:	8000
Maximum Vertex Image Units:	32
Maximum Fragment Image Units:	32
Maximum Pipeline Image Units:	160

Features:
Compute Shader Support:               	1
Image Load/Store Support:             	1

Cycles:
====================================


CPU device capabilities: SSE2 SSE41 AVX2

HIP device capabilities:
	Radeon RX 5500 XT
		hipDeviceAttributeMaxThreadsPerBlock			1024
		hipDeviceAttributeMaxBlockDimX			1024
		hipDeviceAttributeMaxBlockDimY			1024
		hipDeviceAttributeMaxBlockDimZ			1024
		hipDeviceAttributeMaxGridDimX			2147483647
		hipDeviceAttributeMaxGridDimY			65536
		hipDeviceAttributeMaxGridDimZ			65536
		hipDeviceAttributeMaxSharedMemoryPerBlock			65536
		hipDeviceAttributeTotalConstantMemory			2147483647
		hipDeviceAttributeWarpSize			32
		hipDeviceAttributeMaxPitch			2147483647
		hipDeviceAttributeMaxRegistersPerBlock			0
		hipDeviceAttributeClockRate			1717000
		hipDeviceAttributeTextureAlignment			256
		hipDeviceAttributeMultiprocessorCount			11
		hipDeviceAttributeKernelExecTimeout			0
		hipDeviceAttributeIntegrated			0
		hipDeviceAttributeCanMapHostMemory			1
		hipDeviceAttributeComputeMode			0
		hipDeviceAttributeMaxTexture1DWidth			16384
		hipDeviceAttributeMaxTexture2DWidth			16384
		hipDeviceAttributeMaxTexture2DHeight			16384
		hipDeviceAttributeMaxTexture3DWidth			2048
		hipDeviceAttributeMaxTexture3DHeight			2048
		hipDeviceAttributeMaxTexture3DDepth			2048
		hipDeviceAttributeConcurrentKernels			1
		hipDeviceAttributeEccEnabled			0
		hipDeviceAttributeMemoryClockRate			875000
		hipDeviceAttributeMemoryBusWidth			0
		hipDeviceAttributeL2CacheSize			4194304
		hipDeviceAttributeMaxThreadsPerMultiProcessor			2560
		hipDeviceAttributeComputeCapabilityMajor			10
		hipDeviceAttributeComputeCapabilityMinor			1
		hipDeviceAttributeMaxSharedMemoryPerMultiprocessor			65536
		hipDeviceAttributeManagedMemory			0
		hipDeviceAttributeIsMultiGpuBoard			0


Enabled add-ons:
====================================

io_mesh_stl (version: (1, 1, 3), path: C:\Blender\stable\blender-4.0\4.0\scripts\addons\io_mesh_stl\__init__.py)
io_mesh_uv_layout (version: (1, 1, 6), path: C:\Blender\stable\blender-4.0\4.0\scripts\addons\io_mesh_uv_layout\__init__.py)
io_scene_fbx (version: (5, 8, 13), path: C:\Blender\stable\blender-4.0\4.0\scripts\addons\io_scene_fbx\__init__.py)
io_scene_gltf2 (version: (4, 0, 44), path: C:\Blender\stable\blender-4.0\4.0\scripts\addons\io_scene_gltf2\__init__.py)
mesh_f2 (version: (1, 8, 4), path: C:\Blender\stable\blender-4.0\4.0\scripts\addons\mesh_f2.py)
mesh_looptools (version: (4, 7, 7), path: C:\Blender\stable\blender-4.0\4.0\scripts\addons\mesh_looptools.py)
magic_uv (version: (6, 7, 0), path: C:\Blender\stable\blender-4.0\4.0\scripts\addons\magic_uv\__init__.py)
EdgeFlow (version: (0, 8), path: C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\EdgeFlow\__init__.py)
cycles (version: (), path: C:\Blender\stable\blender-4.0\4.0\scripts\addons\cycles\__init__.py)
node_wrangler (version: (3, 47), path: C:\Blender\stable\blender-4.0\4.0\scripts\addons\node_wrangler\__init__.py)
node_arrange (version: (0, 2, 2), path: C:\Blender\stable\blender-4.0\4.0\scripts\addons\node_arrange.py)
Texel_Density_2023_2_Bl400 (version: (2023, 2), path: C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Texel_Density_2023_2_Bl400\__init__.py)
add_mesh_extra_objects (version: (0, 3, 9), path: C:\Blender\stable\blender-4.0\4.0\scripts\addons\add_mesh_extra_objects\__init__.py)
Boxcutter (version: (7, 19, 18), path: C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Boxcutter\__init__.py)
HOps (version: (0, 9, 87, 37), path: C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HOps\__init__.py)
UV-Packer (version: (1, 4, 0), path: C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\UV-Packer\__init__.py)
polyhavenassets (version: (1, 1, 6), path: C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\polyhavenassets\__init__.py)
TexTools_1_6_1 (version: (1, 6, 1), path: C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\TexTools_1_6_1\__init__.py)
lighting_tri_lights (version: (0, 1, 4), path: C:\Blender\stable\blender-4.0\4.0\scripts\addons\lighting_tri_lights.py)
rprblender (version: (3, 6, 10), path: C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\__init__.py)
```

**Comment by canonex** [comment]
I confirm that Blender crashes for a similar error with a default cube and a new created primitive, after ~2 seconds.

```
$ ./blender
2025-05-27 16:25:19,712 INFO rpr.engine.init [140238959662976]:  Core version: 3.1.4 build 0x2cb14e23
2025-05-27 16:25:19,714 INFO rpr.engine.init [140238959662976]:  RIF version: 1.7.3 build 0x1c7b817e
Hardware raytracing support detected
rna_uiItemR: property not found: CyclesMaterialSettings.displacement_method
/home/crickyx/.config/blender/4.4/scripts/addons/rprblender/ui/material.py:149
rna_uiItemR: property not found: RPR_RenderProperties.render_quality
/home/crickyx/.config/blender/4.4/scripts/addons/rprblender/ui/view3d.py:41
2025-05-27 16:25:28,618 WARNING rpr.export.node [140236208207488]:  Ignoring unsupported node <bpy_struct, ShaderNodeLightPath("Light Path") at 0x7f8b98989108, evaluated> <bpy_struct, Material("FloorHidden") at 0x7f8b98947308, evaluated>
rna_uiItemR: property not found: CyclesMaterialSettings.displacement_method
/home/crickyx/.config/blender/4.4/scripts/addons/rprblender/ui/material.py:149
rna_uiItemR: property not found: CyclesMaterialSettings.displacement_method
/home/crickyx/.config/blender/4.4/scripts/addons/rprblender/ui/material.py:149
2025-05-27 16:25:33,144 WARNING rpr.export.node [140236208207488]:  Ignoring unsupported node <bpy_struct, ShaderNodeLightPath("Light Path") at 0x7f8aaa8d7108, evaluated> <bpy_struct, Material("FloorHidden") at 0x7f8aaa895308, evaluated>
rna_uiItemR: property not found: CyclesMaterialSettings.displacement_method
/home/crickyx/.config/blender/4.4/scripts/addons/rprblender/ui/material.py:149
terminate called after throwing an instance of 'Tahoe::Exception'
  what():  std::exception
Annullato
```
and crash.


My system:

version: 4.4.3, branch: blender-v4.4-release
platform: 'Linux-6.1.0-37-amd64-x86_64-with-glibc2.36', Debian Bookworm
windowing environment: 'X11'
Python: version: 3.11.11
GPU: 'NVIDIA GeForce RTX 4070 Laptop GPU/PCIe/SSE2'
version:	'4.6.0 NVIDIA 535.247.01'
