### ISSUE TITLE
Problems Installing Prorender Addon 3.6.10 on Blender 4.0

### ISSUE THREAD

**Issue by rafamas34** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#694]
## System setup
 (Windows 10, AMD RX 580, Intel(R) Core(TM) i5-4460, Blender 4.0 version, Prorender 3.6.10 version)

## Detailed Description
I downloaded and installed Blender version 4.0. When I tried to install the ProRender 3.6.10 addon, an error window appeared during the installation. Please fix this issue as soon as possible.

![Sem título](https://github.com/user-attachments/assets/34415a21-987f-44cc-abcf-1b8cfd91c80b)

## Blender Info Log (Error)
bpy.context.space_data.system_bookmarks_active = 3
Modules Installed () from 'C:\\Users\\Rafa\\Downloads\\RadeonProRenderBlenderAddon-3.6.10.zip' into 'C:\\Users\\Rafa\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons'
bpy.data.window_managers["WinMan"].addon_search = "pro"
Modules Installed (rprblender) from 'C:\\Users\\Rafa\\Downloads\\RadeonProRenderForBlender_3.6.10_Windows.release.zip' into 'C:\\Users\\Rafa\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Rafa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\__init__.py", line 40, in <module>
    from .engine.engine import Engine
  File "C:\Users\Rafa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\engine\__init__.py", line 119, in <module>
    pyrpr2.Context.load_devices()
  File "C:\Users\Rafa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\pyrpr2.py", line 29, in load_devices
    super().load_devices()
  File "C:\Users\Rafa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\pyrpr.py", line 231, in load_devices
    device = get_device(create_flag, getattr(pyrprwrap, 'CONTEXT_GPU%d_NAME' % i))
  File "C:\Users\Rafa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\pyrpr.py", line 223, in get_device
    raise err
  File "C:\Users\Rafa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\pyrpr.py", line 212, in get_device
    context = cls(create_flag)
  File "C:\Users\Rafa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\pyrpr2.py", line 23, in __init__
    super().__init__(flags, props, use_cache)
  File "C:\Users\Rafa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\pyrpr.py", line 256, in __init__
    CreateContext(API_VERSION, [self.plugin_id], 1, flags,
  File "C:\Users\Rafa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\pyrpr.py", line 72, in wrapped
    raise CoreError(status, f.__name__, argv, module_name)
pyrpr.CoreError: RPR call CreateContext(3145988, [0], 1, 1, <cdata 'void *' NULL>, b'C:\\Users\\Rafa\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\rprblender\\.cache\\0x300104_rpr2', <pyrpr2.Context object at 0x000002383FEE7EE0>) returned error code <-4> with error message: ''

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Rafa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\__init__.py", line 40, in <module>
    from .engine.engine import Engine
  File "C:\Users\Rafa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\engine\__init__.py", line 119, in <module>
    pyrpr2.Context.load_devices()
  File "C:\Users\Rafa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\pyrpr2.py", line 29, in load_devices
    super().load_devices()
  File "C:\Users\Rafa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\pyrpr.py", line 231, in load_devices
    device = get_device(create_flag, getattr(pyrprwrap, 'CONTEXT_GPU%d_NAME' % i))
  File "C:\Users\Rafa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\pyrpr.py", line 223, in get_device
    raise err
  File "C:\Users\Rafa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\pyrpr.py", line 212, in get_device
    context = cls(create_flag)
  File "C:\Users\Rafa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\pyrpr2.py", line 23, in __init__
    super().__init__(flags, props, use_cache)
  File "C:\Users\Rafa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\pyrpr.py", line 256, in __init__
    CreateContext(API_VERSION, [self.plugin_id], 1, flags,
  File "C:\Users\Rafa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rprblender\pyrpr.py", line 72, in wrapped
    raise CoreError(status, f.__name__, argv, module_name)
pyrpr.CoreError: RPR call CreateContext(3145988, [2], 1, 1, <cdata 'void *' NULL>, b'C:\\Users\\Rafa\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\rprblender\\.cache\\0x300104_rpr2', <pyrpr2.Context object at 0x000002383FEE5210>) returned error code <-4> with error message: ''

**Comment by darrieusCrdva** [comment]
Hello, I have the same problem (Windows 10, AMD RX 570, Intel(R) Core(TM) i5-6500, Blender version 4.0, Prorender version 3.6.10). Is there still no explanation why it happens? Has it already been solved?

**Comment by takahiroharada** [comment]
The GPU seems not be supported in HIP, thus failing. 
https://rocm.docs.amd.com/projects/install-on-windows/en/latest/reference/system-requirements.html
